### ISSUE TITLE
Block synchronization exception

### ISSUE THREAD

**Issue by lynAzrael** [paritytech/substrate-api-sidecar#1046]
It returns some error info when I try to use api-sidecar to sync block 1790151 on astar blockchain.

Start log:
```
SAS:
  📦 LOG:
     ✅ LEVEL: "info"
     ✅ JSON: false
     ✅ FILTER_RPC: false
     ✅ STRIP_ANSI: false
  📦 SUBSTRATE:
     ✅ WS_URL: "wss://astar.public.blastapi.io"
     ✅ TYPES_BUNDLE: undefined
     ✅ TYPES_CHAIN: undefined
     ✅ TYPES_SPEC: undefined
     ✅ TYPES: undefined
  📦 EXPRESS:
     ✅ BIND_HOST: "127.0.0.1"
     ✅ PORT: 9090
2022-09-05 15:46:15 info: Version: 12.4.2
2022-09-05 15:46:17 info: Connected to chain Astar on the astar client at wss://astar.public.blastapi.io
2022-09-05 15:46:17 info: Listening on http://127.0.0.1:9090/
2022-09-05 15:46:17 info: Check the root endpoint (http://127.0.0.1:9090/) to see the available endpoints for the current node
```

```bash
curl -XGET http://127.0.0.1:9090/blocks/1790151 | jq -r
{
    "code": 500,
    "message": "1: Unable to query dispatch info.: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\nWASM backtrace:\n\n    0: 0x365eb3 - <unknown>!rust_begin_unwind\n    1: 0x2d3ec6 - <unknown>!core::panicking::panic_fmt::h18b15be283411c65\n    2: 0x1d42a0 …",
    "stack": "RpcError: 1: Unable to query dispatch info.: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\nWASM backtrace:\n\n    0: 0x365eb3 - <unknown>!rust_begin_unwind\n    1: 0x2d3ec6 - <unknown>!core::panicking::panic_fmt::h18b15be283411c65\n    2: 0x1d42a0 …\n    at checkError (/Users/lilin/Desktop/work/src/blockchain-managers/astar-manager/libs/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:34:11)\n    at RpcCoder.decodeResponse (/Users/lilin/Desktop/work/src/blockchain-managers/astar-manager/libs/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:54:5)\n    at WsProvider.value (/Users/lilin/Desktop/work/src/blockchain-managers/astar-manager/libs/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:297:90)\n    at W3CWebSocket.value [as onmessage] (/Users/lilin/Desktop/work/src/blockchain-managers/astar-manager/libs/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:277:153)\n    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/lilin/Desktop/work/src/blockchain-managers/astar-manager/libs/substrate-api-sidecar/node_modules/yaeti/lib/EventTarget.js:107:17)\n    at W3CWebSocket.onMessage (/Users/lilin/Desktop/work/src/blockchain-managers/astar-manager/libs/substrate-api-sidecar/node_modules/websocket/lib/W3CWebSocket.js:234:14)\n    at WebSocketConnection.<anonymous> (/Users/lilin/Desktop/work/src/blockchain-managers/astar-manager/libs/substrate-api-sidecar/node_modules/websocket/lib/W3CWebSocket.js:205:19)\n    at WebSocketConnection.emit (node:events:513:28)\n    at WebSocketConnection.processFrame (/Users/lilin/Desktop/work/src/blockchain-managers/astar-manager/libs/substrate-api-sidecar/node_modules/websocket/lib/WebSocketConnection.js:554:26)\n    at /Users/lilin/Desktop/work/src/blockchain-managers/astar-manager/libs/substrate-api-sidecar/node_modules/websocket/lib/WebSocketConnection.js:323:40",
    "level": "error"
}
```

**Comment by TarikGul** [comment]
Hey @lynAzrael, so after some quick reproducing I am not totally sure what is happening. I was able to reproduce this both in Sidecar, as well as polkadot-js. I will keep looking into it and keep you updated.

**Comment by lynAzrael** [comment]
Hi @TarikGul ,Thank you for your reply. I tried the subsequent block synchronization and it is normal, there may be some special information in this block

**Comment by TarikGul** [comment]
From what we were chatting about, it could be a misalignment of of runtime api hashes to versions for the specific queryInfo call. I'll need to pull down the information from Astar to confirm, but like you said it could also be some special information in the block as well.
