### ISSUE TITLE
Polkadot and Kusama use  /blocks/head  err

### ISSUE THREAD

**Issue by LXHLeaner** [paritytech/substrate-api-sidecar#1058]
**Description**

Polkadot and Kusama use  /blocks/head  err

**message**

"createType(RuntimeDispatchInfo):: Struct: failed on weight: u64:: Assertion failed"

**stack**

"Error: createType(RuntimeDispatchInfo):: Struct: failed on weight: u64:: Assertion failed
    at createTypeUnsafe (/Users/lc/Documents/TestGoProject/src/karura/substrate-api-sidecar/node_modules/@polkadot/types-create/cjs/create/type.js:73:18)
    at TypeRegistry.createTypeUnsafe (/Users/lc/Documents/TestGoProject/src/karura/substrate-api-sidecar/node_modules/@polkadot/types/cjs/create/registry.js:353:46)
    at RpcCore._formatOutput (/Users/lc/Documents/TestGoProject/src/karura/substrate-api-sidecar/node_modules/@polkadot/rpc-core/cjs/bundle.js:427:21)
    at RpcCore._formatResult (/Users/lc/Documents/TestGoProject/src/karura/substrate-api-sidecar/node_modules/@polkadot/rpc-core/cjs/bundle.js:232:27)
    at callWithRegistry (/Users/lc/Documents/TestGoProject/src/karura/substrate-api-sidecar/node_modules/@polkadot/rpc-core/cjs/bundle.js:260:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)"

**Comment by TarikGul** [comment]
Closing in favor of: https://github.com/paritytech/substrate-api-sidecar/issues/1057

This is a known issue.
