### ISSUE TITLE
Cannot read property 'extrinsicBaseWeight' of undefined

### ISSUE THREAD

**Issue by zhenghq** [paritytech/substrate-api-sidecar#135]
Internal Error: TypeError: Cannot read property 'extrinsicBaseWeight' of undefined

**Comment by emostov** [comment]
Can you elaborate on the circumstances that led to this error?

Node endpoint? (chain name, spec version, ws url if a public endpoint, etc)

Exact sidecar route?

Any logging info from the terminal Sidecar was running on?

**Comment by zhenghq** [comment]
## polka node

```
work@polka01:~$ sudo systemctl status  polka.service
● polka.service - polka service
     Loaded: loaded (/lib/systemd/system/polka.service; disabled; vendor preset: enabled)
     Active: active (running) since Fri 2020-07-03 11:31:43 CST; 18ms ago
   Main PID: 116297 (polkadot)
      Tasks: 5 (limit: 9487)
     Memory: 3.6M
     CGroup: /system.slice/polka.service
             └─116297 /home/work/bin/polkadot --rpc-external --ws-external --pruning=archive --chain kusama --base-path=/data01/polka_data

Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43      KUSAMA FOUNDATION
Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43 ----------------------------
Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43 Parity Polkadot
Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43 ✌️  version 0.8.12-03067290-x86_64-linux-gnu
Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43 ❤️  by Parity Technologies <admin@parity.io>, 2017-2020
Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43 📋 Chain specification: Kusama
Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43 🏷  Node name: shivering-earthquake-8154
Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43 👤 Role: FULL
Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43 💾 Database: RocksDb at /data01/polka_data/chains/ksmcc3/db
Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43 ⛓  Native runtime: kusama-2012 (parity-kusama-0.tx1.au2)
```


## substrate-api-sidecar

```
work@polka01:~/substrate-api-sidecar-0.10.0$ node -v
v12.18.1

ws url endpoint :  
WS_URL= 'ws://127.0.0.1:9944'

work@polka01:~/substrate-api-sidecar-0.10.0$ yarn start
yarn run v1.22.4
$ yarn run build && yarn run main
$ tsc
$ node ./build/src/main.js
Running on http://127.0.0.1:8080/
```

## parse

```
Python 3.7.7 (default, Jul  2 2020, 12:01:08)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import requests

In [2]: url = "http://127.0.0.1:8080/block/95758"

In [3]: requests.get(url).ok
Out[3]: False
```
The error happened when I executed command above

```
Internal Error: TypeError: Cannot read property 'extrinsicBaseWeight' of undefined
    at ApiHandler.fetchBlock (/home/work/substrate-api-sidecar-0.10.0/build/src/ApiHandler.js:137:55)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/work/substrate-api-sidecar-0.10.0/build/src/main.js:146:16
    at async /home/work/substrate-api-sidecar-0.10.0/build/src/main.js:61:50
127.0.0.1 - - [03/Jul/2020:03:38:51 +0000] "GET /block/95758 HTTP/1.1" 500 26 "-" "python-requests/2.22.0"

```

**Comment by zhenghq** [comment]
> Thank you for the feedback. Can you elaborate on the circumstances that led to this error? Below are some questions that will help us to narrow down the source of the issue. It would be great if you can fill in those details and any other info you feel is worth mentioning.
> 
> * Node endpoint? (chain name, spec version, ws url if a public endpoint, etc)
> * Exact sidecar route?
> * Any logging info from the terminal Sidecar was running on?

## polka node

```
work@polka01:~$ sudo systemctl status  polka.service
● polka.service - polka service
     Loaded: loaded (/lib/systemd/system/polka.service; disabled; vendor preset: enabled)
     Active: active (running) since Fri 2020-07-03 11:31:43 CST; 18ms ago
   Main PID: 116297 (polkadot)
      Tasks: 5 (limit: 9487)
     Memory: 3.6M
     CGroup: /system.slice/polka.service
             └─116297 /home/work/bin/polkadot --rpc-external --ws-external --pruning=archive --chain kusama --base-path=/data01/polka_data

Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43      KUSAMA FOUNDATION
Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43 ----------------------------
Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43 Parity Polkadot
Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43 ✌️  version 0.8.12-03067290-x86_64-linux-gnu
Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43 ❤️  by Parity Technologies <admin@parity.io>, 2017-2020
Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43 📋 Chain specification: Kusama
Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43 🏷  Node name: shivering-earthquake-8154
Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43 👤 Role: FULL
Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43 💾 Database: RocksDb at /data01/polka_data/chains/ksmcc3/db
Jul 03 11:31:43 polka01.bj.jq polkadot[116297]: 2020-07-03 11:31:43 ⛓  Native runtime: kusama-2012 (parity-kusama-0.tx1.au2)
```


## substrate-api-sidecar

```
work@polka01:~/substrate-api-sidecar-0.10.0$ node -v
v12.18.1

ws url endpoint :  
WS_URL= 'ws://127.0.0.1:9944'

work@polka01:~/substrate-api-sidecar-0.10.0$ yarn start
yarn run v1.22.4
$ yarn run build && yarn run main
$ tsc
$ node ./build/src/main.js
Running on http://127.0.0.1:8080/
```

## parse

```
Python 3.7.7 (default, Jul  2 2020, 12:01:08)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import requests

In [2]: url = "http://127.0.0.1:8080/block/95758"

In [3]: requests.get(url).ok
Out[3]: False
```
The error happened when I executed command above

```
Internal Error: TypeError: Cannot read property 'extrinsicBaseWeight' of undefined
    at ApiHandler.fetchBlock (/home/work/substrate-api-sidecar-0.10.0/build/src/ApiHandler.js:137:55)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/work/substrate-api-sidecar-0.10.0/build/src/main.js:146:16
    at async /home/work/substrate-api-sidecar-0.10.0/build/src/main.js:61:50
127.0.0.1 - - [03/Jul/2020:03:38:51 +0000] "GET /block/95758 HTTP/1.1" 500 26 "-" "python-requests/2.22.0"

```
