### ISSUE TITLE
Failed to parse transaction

### ISSUE THREAD

**Issue by Notation** [paritytech/substrate-api-sidecar#1454]
**Description**
hello, I'm using polkadot 1.12.0-b4016902ac7 + @substrate/api-sidecar v19.0.1 of kusama
submit tx got error *Failed to parse transaction*:
```
2024-06-17 14:46:46 error: Failed to parse transaction.
 Cause: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding system.remark:: Struct: failed on args: {"remark":"Bytes"}:: decodeU8aStruct: failed at 0x7e5848469a72bf2be4f9861c532829f7… on remark (index 1/1): Bytes:: Bytes length 294786591 exceeds 10485760
 Transaction: 0x450284008415bcb0bef02a2adfdc1dea7efa773ed548faa42ad78cc9a3a6c76ead01e43701fae68d6d2d2d067198c2f23a88d2887bb90baab77bf01b4acefb0929cd859844d55e6ca3625046004a0fcd223c23ee2aa1042c151876e4efaa9fc39733c14285a5024d01000400007e5848469a72bf2be4f9861c532829f706e6a529269537235f6fd49439b8992c0700f2052a01 
 Error: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding system.remark:: Struct: failed on args: {"remark":"Bytes"}:: decodeU8aStruct: failed at 0x7e5848469a72bf2be4f9861c532829f7… on remark (index 1/1): Bytes:: Bytes length 294786591 exceeds 10485760
    at createTypeUnsafe (/usr/local/share/.config/yarn/global/node_modules/@polkadot/types-create/cjs/create/type.js:54:22)
    at TypeRegistry.createTypeUnsafe (/usr/local/share/.config/yarn/global/node_modules/@polkadot/types/cjs/create/registry.js:230:52)
    at newFromValue (/usr/local/share/.config/yarn/global/node_modules/@polkadot/types/cjs/extrinsic/Extrinsic.js:25:21)
    at decodeU8a (/usr/local/share/.config/yarn/global/node_modules/@polkadot/types/cjs/extrinsic/Extrinsic.js:48:12)
    at decodeExtrinsic (/usr/local/share/.config/yarn/global/node_modules/@polkadot/types/cjs/extrinsic/Extrinsic.js:30:16)
    at new GenericExtrinsic (/usr/local/share/.config/yarn/global/node_modules/@polkadot/types/cjs/extrinsic/Extrinsic.js:198:25)
    at new Type (/usr/local/share/.config/yarn/global/node_modules/@polkadot/types/cjs/create/registry.js:278:24)
    at new Submittable (/usr/local/share/.config/yarn/global/node_modules/@polkadot/api/cjs/submittable/createClass.js:55:13)
    at ApiPromise._extrinsics (/usr/local/share/.config/yarn/global/node_modules/@polkadot/api/cjs/submittable/createSubmittable.js:7:27)
    at TransactionSubmitService.submitTransaction (/usr/local/share/.config/yarn/global/node_modules/@substrate/api-sidecar/build/src/services/transaction/TransactionSubmitService.js:31:22)
2024-06-17 14:46:46 warn: POST /transaction 400 2ms
```

**Steps to Reproduce**
simply transfer ksm to another address

**Comment by Imod7** [comment]
Which tool do you use to create the transaction ?

**Comment by enforser** [comment]
I am running into the same error. We have an internal library we built to construct transactions, but there has been no change to the library. The TX being constructed is the same yet I receive this error. Running with the `--dev` flag.

**Comment by TarikGul** [comment]
`CheckMetadataHash` has been added to Kusama - So it would be good to know how you are constructing the transactions.

Are you using polkadot.js?

**Comment by enforser** [comment]
No, we have built our own library to construct transactions since we don't develop in JS. Has the byte encoding for transfer transactions changed with this update?

**Comment by TarikGul** [comment]
Yes its a pretty big change: https://github.com/paritytech/polkadot-sdk/pull/4619

In order to get your transactions working you can just add 1 byte that disables the `metadataHash` functionality, by adding a `mode: 0` which is just `00`. I would just double check on ordering.

**Comment by IkerAlus** [comment]
@enforser sorry if my assumption is wrong, but it seems you are building this software for Gemini. If this is the case, you should know that Parity has a direct support channel on Telegram with Gemini where we posted weeks ago about this breaking change hitting Kusama and Pokadot chains.

**Comment by enforser** [comment]
@IkerAlus you are right, I've just been re-added to the channel. 

@TarikGul thanks for the info above. I'm now constructing transactions to account for these changes 😄

**Comment by Notation** [comment]
problem solved, thanks!
