### ISSUE TITLE
v19.2.1 fails to start

### ISSUE THREAD

**Issue by BulatSaif** [paritytech/substrate-api-sidecar#1508]
**Description**

Last version fails to start

**Steps to Reproduce**

Version: docker.io/parity/substrate-api-sidecar:v19.2.1

**Expected vs. Actual Behavior**

Error:
```
2024-10-10 07:35:37 info: Listening on http://0.0.0.0:8080/
2024-10-10 07:35:37 info: Check the root endpoint (http://0.0.0.0:8080/) to see the available endpoints for the current node
2024-10-10 07:35:44 error: Cannot read properties of undefined (reading 'stack')
 TypeError: Cannot read properties of undefined (reading 'stack')
    at App.getRoutes (/usr/src/app/build/src/App.js:93:33)
    at /usr/src/app/build/src/App.js:83:30
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at next (/usr/src/app/node_modules/router/lib/route.js:159:13)
    at Route.dispatch (/usr/src/app/node_modules/router/lib/route.js:119:3)
    at handle (/usr/src/app/node_modules/router/index.js:428:11)
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at /usr/src/app/node_modules/router/index.js:293:15
    at processParams (/usr/src/app/node_modules/router/index.js:575:12)
    at next (/usr/src/app/node_modules/router/index.js:289:5)
2024-10-10 07:35:44 error: GET / 500 10ms
2024-10-10 07:35:44 error: Cannot read properties of undefined (reading 'stack')
 TypeError: Cannot read properties of undefined (reading 'stack')
    at App.getRoutes (/usr/src/app/build/src/App.js:93:33)
    at /usr/src/app/build/src/App.js:83:30
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at next (/usr/src/app/node_modules/router/lib/route.js:159:13)
    at Route.dispatch (/usr/src/app/node_modules/router/lib/route.js:119:3)
    at handle (/usr/src/app/node_modules/router/index.js:428:11)
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at /usr/src/app/node_modules/router/index.js:293:15
    at processParams (/usr/src/app/node_modules/router/index.js:575:12)
    at next (/usr/src/app/node_modules/router/index.js:289:5)
2024-10-10 07:35:44 error: GET / 500 5ms
2024-10-10 07:35:54 error: Cannot read properties of undefined (reading 'stack')
 TypeError: Cannot read properties of undefined (reading 'stack')
    at App.getRoutes (/usr/src/app/build/src/App.js:93:33)
    at /usr/src/app/build/src/App.js:83:30
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at next (/usr/src/app/node_modules/router/lib/route.js:159:13)
    at Route.dispatch (/usr/src/app/node_modules/router/lib/route.js:119:3)
    at handle (/usr/src/app/node_modules/router/index.js:428:11)
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at /usr/src/app/node_modules/router/index.js:293:15
    at processParams (/usr/src/app/node_modules/router/index.js:575:12)
    at next (/usr/src/app/node_modules/router/index.js:289:5)
2024-10-10 07:35:54 error: GET / 500 2ms
2024-10-10 07:35:54 error: Cannot read properties of undefined (reading 'stack')
 TypeError: Cannot read properties of undefined (reading 'stack')
    at App.getRoutes (/usr/src/app/build/src/App.js:93:33)
    at /usr/src/app/build/src/App.js:83:30
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at next (/usr/src/app/node_modules/router/lib/route.js:159:13)
    at Route.dispatch (/usr/src/app/node_modules/router/lib/route.js:119:3)
    at handle (/usr/src/app/node_modules/router/index.js:428:11)
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at /usr/src/app/node_modules/router/index.js:293:15
    at processParams (/usr/src/app/node_modules/router/index.js:575:12)
    at next (/usr/src/app/node_modules/router/index.js:289:5)
2024-10-10 07:35:54 error: GET / 500 1ms
2024-10-10 07:36:04 error: Cannot read properties of undefined (reading 'stack')
 TypeError: Cannot read properties of undefined (reading 'stack')
    at App.getRoutes (/usr/src/app/build/src/App.js:93:33)
    at /usr/src/app/build/src/App.js:83:30
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at next (/usr/src/app/node_modules/router/lib/route.js:159:13)
    at Route.dispatch (/usr/src/app/node_modules/router/lib/route.js:119:3)
    at handle (/usr/src/app/node_modules/router/index.js:428:11)
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at /usr/src/app/node_modules/router/index.js:293:15
    at processParams (/usr/src/app/node_modules/router/index.js:575:12)
    at next (/usr/src/app/node_modules/router/index.js:289:5)
2024-10-10 07:36:04 error: GET / 500 2ms
2024-10-10 07:36:04 error: Cannot read properties of undefined (reading 'stack')
 TypeError: Cannot read properties of undefined (reading 'stack')
    at App.getRoutes (/usr/src/app/build/src/App.js:93:33)
    at /usr/src/app/build/src/App.js:83:30
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at next (/usr/src/app/node_modules/router/lib/route.js:159:13)
    at Route.dispatch (/usr/src/app/node_modules/router/lib/route.js:119:3)
    at handle (/usr/src/app/node_modules/router/index.js:428:11)
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at /usr/src/app/node_modules/router/index.js:293:15
    at processParams (/usr/src/app/node_modules/router/index.js:575:12)
    at next (/usr/src/app/node_modules/router/index.js:289:5)
2024-10-10 07:36:04 error: GET / 500 2ms
2024-10-10 07:36:04 error: Cannot read properties of undefined (reading 'stack')
 TypeError: Cannot read properties of undefined (reading 'stack')
    at App.getRoutes (/usr/src/app/build/src/App.js:93:33)
    at /usr/src/app/build/src/App.js:83:30
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at next (/usr/src/app/node_modules/router/lib/route.js:159:13)
    at Route.dispatch (/usr/src/app/node_modules/router/lib/route.js:119:3)
    at handle (/usr/src/app/node_modules/router/index.js:428:11)
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at /usr/src/app/node_modules/router/index.js:293:15
    at processParams (/usr/src/app/node_modules/router/index.js:575:12)
    at next (/usr/src/app/node_modules/router/index.js:289:5)
2024-10-10 07:36:04 error: GET / 500 1ms
2024-10-10 07:36:14 error: Cannot read properties of undefined (reading 'stack')
 TypeError: Cannot read properties of undefined (reading 'stack')
    at App.getRoutes (/usr/src/app/build/src/App.js:93:33)
    at /usr/src/app/build/src/App.js:83:30
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at next (/usr/src/app/node_modules/router/lib/route.js:159:13)
    at Route.dispatch (/usr/src/app/node_modules/router/lib/route.js:119:3)
    at handle (/usr/src/app/node_modules/router/index.js:428:11)
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at /usr/src/app/node_modules/router/index.js:293:15
    at processParams (/usr/src/app/node_modules/router/index.js:575:12)
    at next (/usr/src/app/node_modules/router/index.js:289:5)
2024-10-10 07:36:14 error: GET / 500 2ms
2024-10-10 07:36:24 error: Cannot read properties of undefined (reading 'stack')
 TypeError: Cannot read properties of undefined (reading 'stack')
    at App.getRoutes (/usr/src/app/build/src/App.js:93:33)
    at /usr/src/app/build/src/App.js:83:30
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at next (/usr/src/app/node_modules/router/lib/route.js:159:13)
    at Route.dispatch (/usr/src/app/node_modules/router/lib/route.js:119:3)
    at handle (/usr/src/app/node_modules/router/index.js:428:11)
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at /usr/src/app/node_modules/router/index.js:293:15
    at processParams (/usr/src/app/node_modules/router/index.js:575:12)
    at next (/usr/src/app/node_modules/router/index.js:289:5)
2024-10-10 07:36:24 error: GET / 500 1ms
2024-10-10 07:36:34 error: Cannot read properties of undefined (reading 'stack')
 TypeError: Cannot read properties of undefined (reading 'stack')
    at App.getRoutes (/usr/src/app/build/src/App.js:93:33)
    at /usr/src/app/build/src/App.js:83:30
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at next (/usr/src/app/node_modules/router/lib/route.js:159:13)
    at Route.dispatch (/usr/src/app/node_modules/router/lib/route.js:119:3)
    at handle (/usr/src/app/node_modules/router/index.js:428:11)
    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)
    at /usr/src/app/node_modules/router/index.js:293:15
    at processParams (/usr/src/app/node_modules/router/index.js:575:12)
    at next (/usr/src/app/node_modules/router/index.js:289:5)
2024-10-10 07:36:34 error: GET / 500 2ms
```
cc: @Imod7

**Comment by BulatSaif** [comment]
How to reproduce:
1. start app
```
docker run -e SAS_SUBSTRATE_URL=wss://kusama-rpc.polkadot.io -p 8080:8080 -it --rm  docker.io/parity/substrate-api-sidecar:v19.2.1
```

2. try to connect: 

```
 curl localhost:8080
{"code":500,"message":"Cannot read properties of undefined (reading 'stack')","stack":"TypeError: Cannot read properties of undefined (reading 'stack')\n    at App.getRoutes (/usr/src/app/build/src/App.js:93:33)\n    at /usr/src/app/build/src/App.js:83:30\n    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)\n    at next (/usr/src/app/node_modules/router/lib/route.js:159:13)\n    at Route.dispatch (/usr/src/app/node_modules/router/lib/route.js:119:3)\n    at handle (/usr/src/app/node_modules/router/index.js:428:11)\n    at Layer.handleRequest (/usr/src/app/node_modules/router/lib/layer.js:145:17)\n    at /usr/src/app/node_modules/router/index.js:293:15\n    at processParams (/usr/src/app/node_modules/router/index.js:575:12)\n    at next (/usr/src/app/node_modules/router/index.js:289:5)","level":"error"}
```

**Comment by Imod7** [comment]
@BulatSaif Thank you for reporting this issue and for your valuable feedback. 
A fix was merged earlier today and a new patch release, [v19.2.2](https://github.com/paritytech/substrate-api-sidecar/releases/tag/v19.2.2), has been published to include this fix. Let me know if this resolves the error. Thank you again!

**Comment by BulatSaif** [comment]
Verified, [v19.2.2](https://github.com/paritytech/substrate-api-sidecar/releases/tag/v19.2.2) works as expected. Thank you!
