### ISSUE TITLE
Sidecar Returns 500 for Kusama Block 3392889

### ISSUE THREAD

**Issue by danforbes** [paritytech/substrate-api-sidecar#207]
Error details
```
{
    "code": 500,
    "message": "Missing extrinsic 2 in block 0x0d07f4842c71357e2f143ee1cdb2c61d75bb4381a03e21cc80a8970eba79e7c5",
    "stack": "Error: Missing extrinsic 2 in block 0x0d07f4842c71357e2f143ee1cdb2c61d75bb4381a03e21cc80a8970eba79e7c5\n    at BlocksService.fetchBlock (/app/substrate-api-sidecar/build/src/services/blocks/BlocksService.js:69:31)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async BlocksController.getBlockById (/app/substrate-api-sidecar/build/src/controllers/blocks/BlocksController.js:72:49)\n    at async /app/substrate-api-sidecar/build/src/controllers/AbstractController.js:25:17"
}
```

**Comment by joepetrowski** [comment]
Duplicate https://github.com/paritytech/substrate-api-sidecar/issues/193
