### ISSUE TITLE
balance api get error

### ISSUE THREAD

**Issue by jingniao** [paritytech/substrate-api-sidecar#218]
chain: kusama
substrate-api-sidecar version:  last master `3b1c9b1b74bac8ebd6e4fedaed457db9d7a6704c`
curl `{{apihost}}/balance/GXX9FusH14LKQZyaKsgwaxUMk4bf6oNtT7uXfTQdBnNmuSQ`
```
{
  "code": 500,
  "message": "createType(Vec<BalanceLock>):: Set: Mismatch decoding '111', computed as '15' with TransactionPayment, Transfer, Reserve, Fee",
  "stack": "Error: createType(Vec<BalanceLock>):: Set: Mismatch decoding '111', computed as '15' with TransactionPayment, Transfer, Reserve, Fee\n    at createTypeUnsafe (/var/viabtc/substrate-api-sidecar/node_modules/@polkadot/types/create/createType.js:69:11)\n    at Rpc._formatStorageData (/var/viabtc/substrate-api-sidecar/node_modules/@polkadot/rpc-core/index.js:354:40)\n    at Rpc._formatOutput (/var/viabtc/substrate-api-sidecar/node_modules/@polkadot/rpc-core/index.js:320:21)\n    at MapSubscriber.project (/var/viabtc/substrate-api-sidecar/node_modules/@polkadot/rpc-core/index.js:196:364)\n    at MapSubscriber._next (/var/viabtc/substrate-api-sidecar/node_modules/rxjs/internal/operators/map.js:49:35)\n    at MapSubscriber.Subscriber.next (/var/viabtc/substrate-api-sidecar/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at SwitchMapSubscriber.notifyNext (/var/viabtc/substrate-api-sidecar/node_modules/rxjs/internal/operators/switchMap.js:85:26)\n    at SimpleInnerSubscriber._next (/var/viabtc/substrate-api-sidecar/node_modules/rxjs/internal/innerSubscribe.js:27:21)\n    at SimpleInnerSubscriber.Subscriber.next (/var/viabtc/substrate-api-sidecar/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at CombineLatestSubscriber.notifyNext (/var/viabtc/substrate-api-sidecar/node_modules/rxjs/internal/observable/combineLatest.js:97:34)"
} 
```

**Comment by emostov** [comment]
Seems to be working fine for me and I cannot reproduce the error.

Does the issue resolve if you restart Sidecar?

**Comment by jingniao** [comment]
thank for reply
I update to last commit `41dac62e67c1e5e4e348cfdabbad4e1015f7e60f` `Bump deps (#219)` is ok
