### ISSUE TITLE
Cannot read property 'map' of undefined with error code 500

### ISSUE THREAD

**Issue by xianggy** [paritytech/substrate-api-sidecar#235]
the node.js client get the error:
`http://127.0.0.1:8080/block 
{"code":500,"message":"Cannot read property 'map' of undefined","stack":"TypeError: Cannot read property 'map' of undefined
at BlocksService.createCalcFee (/path/to/substrate-api-sidecar/build/src/services/blocks/BlocksService.js:224:72)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async BlocksService.fetchBlock (/path/to/substrate-api-sidecar/build/src/services/blocks/BlocksService.js:54:52)
at async BlocksController.getLatestBlock (/path/to/substrate-api-sidecar/build/src/controllers/blocks/BlocksController.js:62:49)
at async /path/to/substrate-api-sidecar/build/src/controllers/AbstractController.js:128:9"}`

the substrate-api-sidecar cmd shows:
`127.0.0.1 - - [25/Aug/2020:12:50:45 +0000] "GET /block HTTP/1.1" 500 831 "-" "-"`

substrate-api-sidecar version is the latest v0.14
kusama info:
2020-08-25 20:59:38 This chain is not in any way
2020-08-25 20:59:38       endorsed by the       
2020-08-25 20:59:38      KUSAMA FOUNDATION      
2020-08-25 20:59:38 ----------------------------
2020-08-25 20:59:38 Parity Polkadot
2020-08-25 20:59:38 ✌️  version 0.8.22-unknown-x86_64-linux-gnu
2020-08-25 20:59:38 ❤️  by Parity Technologies <admin@parity.io>, 2017-2020
2020-08-25 20:59:38 📋 Chain specification: Kusama
2020-08-25 20:59:38 🏷  Node name: xxx
2020-08-25 20:59:38 👤 Role: FULL
2020-08-25 20:59:38 💾 Database: RocksDb at /home/xxx/.local/share/polkadot/chains/ksmcc3/db
2020-08-25 20:59:38 ⛓  Native runtime: kusama-2022 (parity-kusama-0.tx2.au2)
2020-08-25 20:59:39 🏷  Local node identity is: 12D3KooWRYXRwsHtehHHkHaN57pvB92TCPnkPb2uFGaoJUBEnQQ1 (legacy representation: Qmaroo4ww6HKWM4m4W7HvzyX168EU231bVW43HxmvKohFU)
2020-08-25 20:59:39 📦 Highest known block at #3759254
2020-08-25 20:59:39 〽️ Prometheus server started at 127.0.0.1:9615

**Comment by emostov** [comment]
Is this a persistent problem or did it just happen once? Are you able to reproduce the issue?

**Comment by xianggy** [comment]
I restarted substrate-api-sidecar and kusama node, and it's ok now. thanks.
