### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by leor-w** [paritytech/substrate-api-sidecar#237]
I try to follow readme run it on my server,but it throws an error.

error info:
```
> yarn start
yarn run v1.22.4
$ yarn run build && yarn run main
$ tsc
$ node ./build/src/main.js
/data/app/dot/substrate-api-sidecar-0.14.0/node_modules/@substrate/calc/calc.js:65
const uint64CvtShim = new BigUint64Array(u32CvtShim.buffer);
                      ^

ReferenceError: BigUint64Array is not defined
    at Object.<anonymous> (/data/app/dot/substrate-api-sidecar-0.14.0/node_modules/@substrate/calc/calc.js:65:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/data/app/dot/substrate-api-sidecar-0.14.0/build/src/services/accounts/AccountsStakingPayoutsService.js:4:16)
    at Module._compile (module.js:652:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by leor-w** [comment]
node.js version issues, update to latest version works fine
