### ISSUE TITLE
Can't Fetching a Block

### ISSUE THREAD

**Issue by qinheqing** [paritytech/substrate-api-sidecar#309]
**Description**

node.js：v12.18.4
os: Ubuntu 18.04LTS 64bit

Request： http://myhost:port/blocks/1803210
response：
`{
    "code": 500,
    "message": "-32603: Unknown error occurred: Client(UnknownBlock(\"State already discarded for BlockId::Hash(0xeee014f2603f72fe64d56e72ede03b5ba9e",
    "stack": "Error: -32603: Unknown error occurred: Client(UnknownBlock(\"State already discarded for BlockId::Hash(0xeee014f2603f72fe64d56e72ede03b5ba9e\n    at RpcCoder._checkError (/opt/node.js/12.18.4/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-provider/coder/index.js:84:13)\n    at RpcCoder.decodeResponse (/opt/node.js/12.18.4/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-provider/coder/index.js:47:10)\n    at WsProvider.value (/opt/node.js/12.18.4/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-provider/ws/Provider.js:215:90)\n    at W3CWebSocket.value [as onmessage] (/opt/node.js/12.18.4/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-provider/ws/Provider.js:195:153)\n    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/opt/node.js/12.18.4/lib/node_modules/@substrate/api-sidecar/node_modules/yaeti/lib/EventTarget.js:107:17)\n    at W3CWebSocket.onMessage (/opt/node.js/12.18.4/lib/node_modules/@substrate/api-sidecar/node_modules/websocket/lib/W3CWebSocket.js:234:14)\n    at WebSocketConnection.<anonymous> (/opt/node.js/12.18.4/lib/node_modules/@substrate/api-sidecar/node_modules/websocket/lib/W3CWebSocket.js:205:19)\n    at WebSocketConnection.emit (events.js:315:20)\n    at WebSocketConnection.processFrame (/opt/node.js/12.18.4/lib/node_modules/@substrate/api-sidecar/node_modules/websocket/lib/WebSocketConnection.js:554:26)\n    at /opt/node.js/12.18.4/lib/node_modules/@substrate/api-sidecar/node_modules/websocket/lib/WebSocketConnection.js:323:40",
    "level": "error"
}`

**Steps to Reproduce**
1. run substrate-api-sidecar and Connected to chain Polkadot on the parity-polkadot client at ws://myhost:port
2. Request http://myhost:port/blocks/1803210

**Expected vs. Actual Behavior**

Backstage log：

2020-09-29 17:03:11 error: GET /blocks/1803210 500 15ms
2020-09-29 17:09:04 error:         RPC-CORE: getRuntimeVersion(at?: BlockHash): RuntimeVersion:: -32603: Unknown error occurred: Client(UnknownBlock("State already discarded for BlockId::Hash(0x676b796fdcde2153c4bd26c5a0f6dda4151
2020-09-29 17:09:04 error:         RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: -32603: Unknown error occurred: Client(UnknownBlock("State already discarded for BlockId::Hash(0x676b796fdcde2153c4bd26c5a0f6dda4151
2020-09-29 17:09:04 error:         RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: -32603: Unknown error occurred: Client(UnknownBlock("State already discarded for BlockId::Hash(0x676b796fdcde2153c4bd26c5a0f6dda4151
2020-09-29 17:09:04 error:         RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: -32603: Unknown error occurred: Client(UnknownBlock("State already discarded for BlockId::Hash(0x676b796fdcde2153c4bd26c5a0f6dda4151
2020-09-29 17:09:04 error: -32603: Unknown error occurred: Client(UnknownBlock("State already discarded for BlockId::Hash(0x676b796fdcde2153c4bd26c5a0f6dda4151 
 Error: -32603: Unknown error occurred: Client(UnknownBlock("State already discarded for BlockId::Hash(0x676b796fdcde2153c4bd26c5a0f6dda4151
    at RpcCoder._checkError (/opt/node.js/12.18.4/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-provider/coder/index.js:84:13)
    at RpcCoder.decodeResponse (/opt/node.js/12.18.4/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-provider/coder/index.js:47:10)
    at WsProvider.value (/opt/node.js/12.18.4/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-provider/ws/Provider.js:215:90)
    at W3CWebSocket.value [as onmessage] (/opt/node.js/12.18.4/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-provider/ws/Provider.js:195:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/opt/node.js/12.18.4/lib/node_modules/@substrate/api-sidecar/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/opt/node.js/12.18.4/lib/node_modules/@substrate/api-sidecar/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/opt/node.js/12.18.4/lib/node_modules/@substrate/api-sidecar/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.processFrame (/opt/node.js/12.18.4/lib/node_modules/@substrate/api-sidecar/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /opt/node.js/12.18.4/lib/node_modules/@substrate/api-sidecar/node_modules/websocket/lib/WebSocketConnection.js:323:40
2020-09-29 17:09:04 error: GET /blocks/0xf1aa3c6c9940eccd25c8e8e46a07400187c5e880e756d3a4f06753fbbf5cc8f3 500 14ms

**Comment by emostov** [comment]
Looks like your node's database may have pruned some info for that block. Make sure to run the option `pruning=archive` for your node.

The error comes from here:
https://github.com/paritytech/substrate/blob/58d6df36f32452027010d7f532c9aaa5ded54570/client/db/src/lib.rs#L1687

**Comment by zebpay-peswani** [comment]
Hi I am getting same issue how did you solved it?
using this command I am getting 
` 0: State database error: Expected pruning mode: constrained`
`./polkadot --chain=westend --name "zeb-testnet" --pruning=archive`

**Comment by emostov** [comment]
@zebpay-peswani can you give the following details

- Command used to run the node
- Screenshot of substrate-api-sidecar env configuration in terminal start up prompt
- Exact error message in sidecar response
- Exact error message in terminal running sidecar

**Comment by zebpay-peswani** [comment]
command to run node `./polkadot --chain=westend --name "zeb-testnet"`
```
command for substrate-api-sidecar ~$ substrate-api-sidecar
SAS:
  📦 LOG:
     ✅ LEVEL: "info"
     ✅ JSON: false
     ✅ FILTER_RPC: false
     ✅ STRIP_ANSI: false
  📦 SUBSTRATE:
     ✅ WS_URL: "ws://127.0.0.1:9944"
  📦 EXPRESS:
     ✅ BIND_HOST: "127.0.0.1"
     ✅ PORT: 8080
2020-12-03 16:09:49 error: API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2020-12-03 16:09:49 error: uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<_Event>".
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<_Event>". 
 UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<_Event>".
{"error":{"code":"ERR_UNHANDLED_REJECTION"},"level":"error","message":"uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<_Event>\".\nUnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<_Event>\".","stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<_Event>\".","exception":true,"date":"Thu Dec 03 2020 16:09:49 GMT+0000 (Coordinated Universal Time)","process":{"pid":9112,"uid":1000,"gid":1000,"cwd":"/home/ubuntu","execPath":"/home/ubuntu/.nvm/versions/node/v15.3.0/bin/node","version":"v15.3.0","argv":["/home/ubuntu/.nvm/versions/node/v15.3.0/bin/node","/home/ubuntu/.nvm/versions/node/v15.3.0/bin/substrate-api-sidecar"],"memoryUsage":{"rss":87248896,"heapTotal":55017472,"heapUsed":22825192,"external":2525754,"arrayBuffers":56281}},"os":{"loadavg":[2.14,2.05,2.11],"uptime":9959957},"trace":[]}
2020-12-03 16:09:50 error: API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2020-12-03 16:09:51 error: API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2020-12-03 16:09:52 error: API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2020-12-03 16:09:53 error: API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
^C2020-12-03 16:09:53 info: Caught interrupt signal, exiting...
```

Error on GET API

```
~$ curl localhost:8080/blocks/1000000

{"code":500,"message":"-32603: Unknown error occurred: Client, UnknownBlock, State already discarded for BlockId::Hash, 0xcdfe7743ad912282612a198ca70e919ace13942cc1a764928dba25bb4dd0803c","stack":"Error: -32603: Unknown error occurred: Client, UnknownBlock, State already discarded for BlockId::Hash, 0xcdfe7743ad912282612a198ca70e919ace13942cc1a764928dba25bb4dd0803c\n    at RpcCoder._checkError (/home/ubuntu/.nvm/versions/node/v15.3.0/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-provider/coder/index.js:84:13)\n    at RpcCoder.decodeResponse (/home/ubuntu/.nvm/versions/node/v15.3.0/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-provider/coder/index.js:47:10)\n    at WsProvider.value (/home/ubuntu/.nvm/versions/node/v15.3.0/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-provider/ws/index.js:212:90)\n    at W3CWebSocket.value [as onmessage] (/home/ubuntu/.nvm/versions/node/v15.3.0/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-provider/ws/index.js:192:153)\n    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/ubuntu/.nvm/versions/node/v15.3.0/lib/node_modules/@substrate/api-sidecar/node_modules/yaeti/lib/EventTarget.js:107:17)\n    at W3CWebSocket.onMessage (/home/ubuntu/.nvm/versions/node/v15.3.0/lib/node_modules/@substrate/api-sidecar/node_modules/websocket/lib/W3CWebSocket.js:234:14)\n    at WebSocketConnection.<anonymous> (/home/ubuntu/.nvm/versions/node/v15.3.0/lib/node_modules/@substrate/api-sidecar/node_modules/websocket/lib/W3CWebSocket.js:205:19)\n    at WebSocketConnection.emit (node:events:376:20)\n    at WebSocketConnection.processFrame (/home/ubuntu/.nvm/versions/node/v15.3.0/lib/node_modules/@substrate/api-sidecar/node_modules/websocket/lib/WebSocketConnection.js:554:26)\n    at /home/ubuntu/.nvm/versions/node/v15.3.0/lib/node_modules/@substrate/api-sidecar/node_modules/websocket/lib/WebSocketConnection.js:323:40","level":"error"}
```

**Comment by emostov** [comment]
It looks like an issue with your node. You need to make sure the node is running in pruning mode. Your node database might be having issues and I would recommend re-syncing a completely new database for your node.

**Comment by qinheqing** [comment]
@zebpay-peswani  
API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed

That  means your substrate-api-sidecar fails to connect to the wallet node and you should check if the wallet node is correct

**Comment by hufengvia** [comment]
> Hi I am getting same issue how did you solved it?
> using this command I am getting
> ` 0: State database error: Expected pruning mode: constrained`
> `./polkadot --chain=westend --name "zeb-testnet" --pruning=archive`

I have the same problem with you , have you been solve the problem now ?

**Comment by emostov** [comment]
@hufengvia The database you are using is not a full `archive` database, so it is missing some data. You need to start your node with a full archive database. You can either try and find somewhere to download the database from or sync a database from scratch.

You can clear your current data base with `./polkadot purge-chain --chain=westend`
