### ISSUE TITLE
substrate-api-sidecar can not work

### ISSUE THREAD

**Issue by zhangsj** [paritytech/substrate-api-sidecar#320]
SAS:
  📦 EXPRESS:
     ✅ LOG_MODE: "errors"
     ✅ BIND_HOST: "0.0.0.0"
     ✅ PORT: 8080
  📦 SUBSTRATE:
     ✅ WS_URL: "ws://127.0.0.1:9944"
2020-10-15 09:54:59        API/INIT: RPC methods not decorated: grandpa_proveFinality
Unable to resolve type BountyIndex, it will fail on construction
Unknown types found, no types for Bounty, BountyIndex
2020-10-15 09:55:00        API/INIT: Error: FATAL: Unable to initialize the API: createType(BountyIndex):: Cannot construct unknown type BountyIndex
    at EventEmitter.value (/usr/src/app/node_modules/@polkadot/api/base/Init.js:85:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1) UnhandledPromiseRejectionWarning: Error: FATAL: Unable to initialize the API: createType(BountyIndex):: Cannot construct unknown type BountyIndex
    at EventEmitter.value (/usr/src/app/node_modules/@polkadot/api/base/Init.js:85:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by emostov** [comment]
Upgrade to v1.0.0-rc3 - you are missing some new types.
