### ISSUE TITLE
Got an error response with edgeware node

### ISSUE THREAD

**Issue by Ljzn** [paritytech/substrate-api-sidecar#329]
**Description**

- Set up an mainnet edgeware node with this docker: https://github.com/yangwao/substrate_playground
- Start sidecar connecting to the websocket port of node
- visit `/blocks/head`
- got an error response

```json
{"code":500,"message":"Cannot read property 'extrinsicBaseWeight' of undefined","stack":"TypeError: Cannot read property 'extrinsicBaseWeight' of undefined\n    at BlocksService.createCalcFee (/usr/src/app/build/src/services/blocks/BlocksService.js:231:55)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async BlocksService.fetchBlock (/usr/src/app/build/src/services/blocks/BlocksService.js:55:52)\n    at async BlocksController.getLatestBlock (/usr/src/app/build/src/controllers/blocks/BlocksController.js:77:49)\n    at async /usr/src/app/build/src/controllers/AbstractController.js:138:9","level":"error"}
```

**Expected vs. Actual Behavior**

Get correct chain head block.

**Comment by emostov** [comment]
Is it clear that sidecar has successfully connected to the node?

Have you set any custom types for edgeware? (See https://github.com/paritytech/substrate-api-sidecar#custom-substrate-types)

**Comment by Ljzn** [comment]
Yes, it responded at `/runtime/spec`
```
{"at":{"height":"771073","hash":"0x60ebaa751a649712e91703738a2d6502b386be6c4f7fbb9dc1d82d3babd448e4"},"authoringVersion":"16","transactionVersion":"1","implVersion":"31","specName":"edgeware","specVersion":"31","chainType":{"Live":null},"properties":{"ss58Format":"7","tokenDecimals":"18","tokenSymbol":"EDG"}}
```

No, I didn't set any chain specific types.

**Comment by emostov** [comment]
I have not tested out Sidecar yet with Edgeware, so there is a chance it may not work. But in order to get it to work you will need to add custom types. This should provide a starting point for the types needed for Edgeware: https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/edgeware.ts

In the coming months Sidecar will build in more explicit support for substrate based chains like Edgeware.

**Comment by Ljzn** [comment]
Thanks, emostov. I will try to figure out how to import the edgeware node types https://github.com/hicommonwealth/edgeware-node-types/blob/master/src/spec/mainnet.ts into the sidecar.

**Comment by emostov** [comment]
Let me know if you get stuck again. I will start working on a more extensive generic substrate chain integration strategy soon

**Comment by Ljzn** [comment]
Hi, @emostov . I made follow changes in the sidecar code:

in `package.json`
```js
// added  in dependencies
    "@edgeware/node-types": "^3.0.7",
```

in `Config.ts`
```js
import { Mainnet } from '@edgeware/node-types';

...

			SUBSTRATE: {
				WS_URL: config.Get(MODULES.SUBSTRATE, CONFIG.WS_URL) as string,
				CUSTOM_TYPES: {
					...configTypes[CONFIG.CUSTOM_TYPES],
					...Mainnet.types
				}
			},
```

After rebuilding and starting the sidecar server, I still got some error when getting `/blocks/head`:

```
2020-11-02 16:35:58 error: Unable to decode storage system.events: createType(Vec<EventRecord>):: Struct: failed on 'data':: Unable to create Enum via index 211, in Normal, Operational, Mandatory
2020-11-02 16:35:58 error:         RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: createType(Vec<EventRecord>):: Struct: failed on 'data':: Unable to create Enum via index 211, in Normal, Operational, Mandatory
2020-11-02 16:35:59 error: Cannot read property 'extrinsicBaseWeight' of undefined 
 TypeError: Cannot read property 'extrinsicBaseWeight' of undefined
    at BlocksService.createCalcFee (/Users/zhanglinjie/Develop/substrate-api-sidecar/build/src/services/blocks/BlocksService.js:231:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async BlocksService.fetchBlock (/Users/zhanglinjie/Develop/substrate-api-sidecar/build/src/services/blocks/BlocksService.js:55:52)
    at async BlocksController.getLatestBlock (/Users/zhanglinjie/Develop/substrate-api-sidecar/build/src/controllers/blocks/BlocksController.js:77:49)
    at async /Users/zhanglinjie/Develop/substrate-api-sidecar/build/src/controllers/AbstractController.js:138:9
```

**Comment by Ljzn** [comment]
I finally made it!

Just add the type into the api in `src/main.ts`:

```
import { Mainnet } from '@edgeware/node-types';
...
	// Instantiate a web socket connection to the node for basic polkadot-js use
	const api = await ApiPromise.create({
		provider: new WsProvider(config.SUBSTRATE.WS_URL),
		...Mainnet
	});
```

**Comment by Ljzn** [comment]
The same problem shows again, and I don't known why.

```
2020-11-04 18:05:47 error: Cannot read property 'extrinsicBaseWeight' of undefined 
 TypeError: Cannot read property 'extrinsicBaseWeight' of undefined
    at BlocksService.createCalcFee (/Users/zhanglinjie/Develop/substrate-api-sidecar/build/src/services/blocks/BlocksService.js:231:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async BlocksService.fetchBlock (/Users/zhanglinjie/Develop/substrate-api-sidecar/build/src/services/blocks/BlocksService.js:55:52)
    at async BlocksController.getBlockById (/Users/zhanglinjie/Develop/substrate-api-sidecar/build/src/controllers/blocks/BlocksController.js:89:49)
    at async /Users/zhanglinjie/Develop/substrate-api-sidecar/build/src/controllers/AbstractController.js:138:9
```

I uploaded the code here: https://github.com/Ljzn/substrate-api-sidecar-for-edgeware

**Comment by emostov** [comment]
I created a branch the appears to be working with the `/blocks` endpoint, but will not calculate partial fees for you.

See https://github.com/paritytech/substrate-api-sidecar/tree/edgeware

**Comment by Ljzn** [comment]
Thank you! I will check it.

**Comment by emostov** [comment]
Sidecar now supports types through polkadot/apps-config so this should no longer be an issue
