### ISSUE TITLE
An error is thrown on startup " Error: Cannot find module '@polkadot/types/codec/StructAny'"

### ISSUE THREAD

**Issue by leor-w** [paritytech/substrate-api-sidecar#340]
**Version**
v1.0.0

**chainnet**
kusama v0.8.26

**Description**
Thrown error at startup 
```
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '@polkadot/types/codec/StructAny'
Require stack:
- /data/app/ksm/substrate-api-sidecar/node_modules/@substrate/api-sidecar/build/src/sanitize/sanitizeNumbers.js
- /data/app/ksm/substrate-api-sidecar/node_modules/@substrate/api-sidecar/build/src/services/pallets/PalletsStorageItemService.js
- /data/app/ksm/substrate-api-sidecar/node_modules/@substrate/api-sidecar/build/src/services/pallets/index.js
- /data/app/ksm/substrate-api-sidecar/node_modules/@substrate/api-sidecar/build/src/services/index.js
- /data/app/ksm/substrate-api-sidecar/node_modules/@substrate/api-sidecar/build/src/controllers/transaction/TransactionDryRunController.js
- /data/app/ksm/substrate-api-sidecar/node_modules/@substrate/api-sidecar/build/src/controllers/transaction/index.js
- /data/app/ksm/substrate-api-sidecar/node_modules/@substrate/api-sidecar/build/src/controllers/index.js
- /data/app/ksm/substrate-api-sidecar/node_modules/@substrate/api-sidecar/build/src/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/data/app/ksm/substrate-api-sidecar/node_modules/@substrate/api-sidecar/build/src/sanitize/sanitizeNumbers.js:8:21)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
```

**Comment by emostov** [comment]
Looks like you have a mismatched version of `@polkadot/api` installed. You will need to make sure in your `package.json` you have

```json
"dependencies": {
    "@polkadot/api": "^2.3.1",
    ...
   }
```
then run `yarn install`. 

Did you get the error installing sidecar from github or from NPM?

**Comment by oggy95** [comment]
Have same issue. 
Package.json:
```
"dependencies": {
    "@polkadot/api": "^2.6.1",
    ...
  },
```
Install via github.

**Comment by emostov** [comment]
@oggy95 Thanks for the info. Do you know what exact commit you are using?

For me, the latest commit on master works (db61ccb2c9fbff9a92fa7fef39996c87351aca60).

**Comment by oggy95** [comment]
@emostov same commit, installed on other server (Ubuntu 18.04, nodejs v12.19.1, yarn 1.22.5), now error like this:
```
yarn run v1.22.5
$ yarn run main
$ node ./build/src/main.js
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module '/root/substrate-api-sidecar/build/src/main.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Installed via npm, error like in topic starter message.

**Comment by emostov** [comment]
Run ```yarn build && yarn start```.  The build operation was removed from the start command so you need to build before running (updated instructions in the README here: https://github.com/paritytech/substrate-api-sidecar#running)

**Comment by emostov** [comment]
I see the NPM install error now; will publish a new release soon that should take care of the issue.

**Comment by emostov** [comment]
Try the latest NPM release, v1.1.0 - should work.

**Comment by oggy95** [comment]
`yarn build && yarn start ` and version v1.1.0 it worked. Thank you!
