### ISSUE TITLE
/blocks/head return error

### ISSUE THREAD

**Issue by xianggy** [paritytech/substrate-api-sidecar#350]
how to solve it, thx.

2020-11-21 17:05:22 error: Cannot read property 'validators' of undefined 
 TypeError: Cannot read property 'validators' of undefined
    at BlocksService.fetchBlock (/Users/xiangguangyue/Workplace/Product/node/substrate-api-sidecar/build/src/services/blocks/BlocksService.js:30:31)
    at BlocksController.getLatestBlock (/Users/xiangguangyue/Workplace/Product/node/substrate-api-sidecar/build/src/controllers/blocks/BlocksController.js:77:68)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/xiangguangyue/Workplace/Product/node/substrate-api-sidecar/build/src/controllers/AbstractController.js:138:9
2020-11-21 17:05:22 error: GET /blocks/head 500 4ms

**Comment by emostov** [comment]
What network are you using sidecar against?

**Comment by xianggy** [comment]
Kulupu.
in BlocksService.ts:
```
		const [{ block }, events, validators=[]] = await Promise.all([
			api.rpc.chain.getBlock(hash),
			this.fetchEvents(api, hash),
			api.query.session.validators.at(hash),  // api.query.session is undefined
		]);
```

**Comment by emostov** [comment]
Sidecar does not yet accommodate Kulupu, but it will in the future. For the time being though, what endpoints are you looking to use? I could possibly create a branch of Sidecar that will have some endpoints work with Kulupu.

**Comment by xianggy** [comment]
Well, thank you very much.
I need some apis for exchange wallet integration:
blocks:
/blocks/head[?finalized=false]
/blocks/{blockId} for the extrinsics details and events
accounts:
/accounts/{accountId}/balance-info
transaction details:
/tx/{txHash}
