### ISSUE TITLE
Westend: Error: createType(Call):: findMetaCall: Unable to find Call with index 0x0900/[9,0]

### ISSUE THREAD

**Issue by islishude** [paritytech/substrate-api-sidecar#384]
Description

code: lastest commit
nodejs: v14 LTS
network: westend testnet
polkadot: v1.8.27

Steps to Reproduce

request for `/blocks/3809155` and get `createType(Call):: findMetaCall: Unable to find Call with index 0x0900/[9,0]`

```
2021-01-13 14:19:32 error: REGISTRY: Error: findMetaCall: Unable to find Call with index 0x0900/[9,0]
    at assert (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/util/assert.js:34:11)
    at assertReturn (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/util/assert.js:44:3)
    at TypeRegistry.findMetaCall (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/create/registry.js:274:35)
    at decodeCallViaObject (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/generic/Call.js:57:34)
    at decodeCall (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/generic/Call.js:100:12)
    at new GenericCall (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/generic/Call.js:129:21)
    at new Type (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/create/registry.js:311:16)
    at initType (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/create/createType.js:49:19)
    at createTypeUnsafe (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/create/createType.js:69:12)
    at createType (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/create/createType.js:84:10)
2021-01-13 14:19:32 error: createType(Call):: findMetaCall: Unable to find Call with index 0x0900/[9,0] 
 Error: createType(Call):: findMetaCall: Unable to find Call with index 0x0900/[9,0]
    at createTypeUnsafe (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/create/createType.js:72:11)
    at createType (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/create/createType.js:84:10)
    at TypeRegistry.createType (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/create/registry.js:268:39)
    at /project/github.com/polkadot-js/substrate-api-sidecar/build/src/services/blocks/BlocksService.js:145:41
        -> /project/github.com/polkadot-js/substrate-api-sidecar/src/services/blocks/BlocksService.ts:226:32
    at Array.map (<anonymous>)
    at Array.map (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/codec/AbstractArray.js:151:27)
    at BlocksService.extractExtrinsics (/project/github.com/polkadot-js/substrate-api-sidecar/build/src/services/blocks/BlocksService.js:142:33)
        -> /project/github.com/polkadot-js/substrate-api-sidecar/src/services/blocks/BlocksService.ts:216:27
    at BlocksService.fetchBlock (/project/github.com/polkadot-js/substrate-api-sidecar/build/src/services/blocks/BlocksService.js:52:45)
        -> /project/github.com/polkadot-js/substrate-api-sidecar/src/services/blocks/BlocksService.ts:81:39
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async BlocksController.getBlockById (/project/github.com/polkadot-js/substrate-api-sidecar/build/src/controllers/blocks/BlocksController.js:92:49)
        -> /project/github.com/polkadot-js/substrate-api-sidecar/src/controllers/blocks/BlocksController.ts:125:4
```

Expected vs. Actual Behavior

should no error here

**Comment by emostov** [comment]
This relates to: https://github.com/paritytech/substrate/pull/7228

It is failing to decode `finalityTracker.finalHint`, which was removed. We will look into a solution.

**Comment by emostov** [comment]
We need to investigate if this will affect non-testnet runtimes.

**Comment by emostov** [comment]
This is affecting a lot of blocks, including older blocks on polkadot. The issue is coming from using an incorrect registry when trying to create `Call`s.
