### ISSUE TITLE
failed to request `/blocks/3337808`

### ISSUE THREAD

**Issue by islishude** [paritytech/substrate-api-sidecar#389]
**Description**

nodejs version: v14 LTS
polkadot version: 1.8.26-1
sidecar version: latest commit
network: polkadot mainnet

**Steps to Reproduce**

request `/blocks/3337808`

```
2021-01-14 19:31:55 error: REGISTRY: Error: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding staking.submitElectionSolutionUnsigned:: Struct: failed on args: {"winners":"Vec<ValidatorIndex>","compact":"CompactAssignments","score":"ElectionScore","era":"EraIndex","size":"ElectionSize"}:: Maximum call stack size exceeded
    at /project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/codec/Struct.js:70:13
    at Array.reduce (<anonymous>)
    at decodeStructFromObject (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/codec/Struct.js:24:29)
    at decodeStruct (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/codec/Struct.js:111:10)
    at new Struct (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/codec/Struct.js:132:26)
    at new <anonymous> (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/codec/Struct.js:150:9)
    at new Type (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/create/registry.js:311:16)
    at initType (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/create/createType.js:49:19)
    at createTypeUnsafe (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/types/create/createType.js:69:12)
    at RpcCore._formatOutput (/project/github.com/polkadot-js/substrate-api-sidecar/node_modules/@polkadot/rpc-core/index.js:394:41)
2021-01-14 19:31:55 error: RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding staking.submitElectionSolutionUnsigned:: Struct: failed on args: {"winners":"Vec<ValidatorIndex>","compact":"CompactAssignments","score":"ElectionScore","era":"EraIndex","size":"ElectionSize"}:: Maximum call stack size exceeded
```

**Expected vs. Actual Behavior**

**Comment by emostov** [comment]
I can confirm replication of this error. I believe it relates to the fact that the `submit_election_solution` inherent is massive and it looks like the call stack blows when trying to decode the arguments to the call.

```
Call: failed decoding staking.submitElectionSolutionUnsigned:: Struct: failed on args: {"winners":"Vec<ValidatorIndex>","compact":"CompactAssignments","score":"ElectionScore","era":"EraIndex","size":"ElectionSize"}:: Maximum call stack size exceeded
```

The actual call is here: Call: failed decoding staking.submitElectionSolutionUnsigned:: Struct: failed on args: {"winners":"Vec<ValidatorIndex>","compact":"CompactAssignments","score":"ElectionScore","era":"EraIndex","size":"ElectionSize"}:: Maximum call stack size exceeded
```
The inherent can be found here:
https://polkascan.io/polkadot/inherent/3337808-1

At the very least api-sidecar should not fail, ideally though it would be able to decode it.

**Comment by emostov** [comment]
The short term hack would be to run the service with the command: `node --stack_size=1300 ./build/src/main.js`
