### ISSUE TITLE
Various problems with 3.0.0 against 0.8.27

### ISSUE THREAD

**Issue by ngallagher** [paritytech/substrate-api-sidecar#417]
I am seeing the following errors in the logs, though the HTTP interface seems fine.

```
2021-02-02 23:04:05 error: REGISTRY: Error: createType(ExtrinsicSignatureV4):: Unable to create Enum via index 29, in Ed25519, Sr25519, Ecdsa
    at createTypeUnsafe (/build/polkadot/sidecar/node_modules/@polkadot/types/create/createType.js:72:11)
    at createType (/build/polkadot/sidecar/node_modules/@polkadot/types/create/createType.js:84:10)
    at TypeRegistry.createType (/build/polkadot/sidecar/node_modules/@polkadot/types/create/registry.js:297:39)
    at Function.decodeExtrinsic (/build/polkadot/sidecar/node_modules/@polkadot/types/extrinsic/v4/Extrinsic.js:44:34)
    at new GenericExtrinsicV4 (/build/polkadot/sidecar/node_modules/@polkadot/types/extrinsic/v4/Extrinsic.js:30:27)
```

Additionally when I attempt a dry run it seems unable to find the transfer method, even though the metadata decoder has it? 

```
{
   "code": "500",
   "error": "Unable to dry-run transaction",
   "transaction": "0x3902848638559291b4ab4bfc7f5c1aa898c1f0bf1d09d04b10c9027169d7c5ccb53c000174044da941d1e43e8957a72b423590c02205a382ffacad4ac0b1260d2405b47f48930825274e7377b8a9207fba834aba465e77e687d90455de7280f722214d8a00000004004a83f1c09be797bc3d9adce29818368b276a84e6b545ced492c25c948978d7f80b008cb6611e01",
   "cause": "-32601: Method not found",
   "stack": "Error: -32601: Method not found
    at RpcCoder._checkError (/build/polkadot/sidecar/node_modules/@polkadot/rpc-provider/coder/index.js:84:13)
    at RpcCoder.decodeResponse (/build/polkadot/sidecar/node_modules/@polkadot/rpc-provider/coder/index.js:47:10)
    at WsProvider.value (/build/polkadot/sidecar/node_modules/@polkadot/rpc-provider/ws/index.js:214:90)
    at W3CWebSocket.value [as onmessage] (/build/polkadot/sidecar/node_modules/@polkadot/rpc-provider/ws/index.js:194:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/build/polkadot/sidecar/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/build/polkadot/sidecar/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/build/polkadot/sidecar/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (node:events:379:20)
    at WebSocketConnection.processFrame (/build/polkadot/sidecar/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /build/polkadot/sidecar/node_modules/websocket/lib/WebSocketConnection.js:323:40",
}
```

**Comment by ngallagher** [comment]
Another one I see frequently... (wondering is there an underlying configuration issue, or just incompatible with 0.8.27?)

```
2021-02-02 23:04:05 error: REGISTRY: Error: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: Unable to create Enum via index 29, in Ed25519, Sr25519, Ecdsa
    at /build/polkadot/sidecar/node_modules/@polkadot/types/codec/Struct.js:70:13
    at Array.reduce (<anonymous>)
    at decodeStructFromObject (/build/polkadot/sidecar/node_modules/@polkadot/types/codec/Struct.js:24:29)
    at decodeStruct (/build/polkadot/sidecar/node_modules/@polkadot/types/codec/Struct.js:111:10)
    at new Struct (/build/polkadot/sidecar/node_modules/@polkadot/types/codec/Struct.js:132:26)
    at new <anonymous> (/build/polkadot/sidecar/node_modules/@polkadot/types/codec/Struct.js:150:9)
```

**Comment by ngallagher** [comment]
Much of the issues go for version 3.0.1, however I still see the following, when I submit a transaction

```
{
   "code": "500",
   "error": "Failed to parse transaction.",
   "transaction": "0x3902848638559291b4ab4bfc7f5c1aa898c1f0bf1d09d04b10c9027169d7c5ccb53c0001fc38386fbaded385ca03776a63dfe7fac8507cffa3088c1321ce68c1f870a7147f583be3ec76e696b9b0a49aa283c0ddb0122885b501ef0115770fb099db548100000004004a83f1c09be797bc3d9adce29818368b276a84e6b545ced492c25c948978d7f80b008cb6611e01",
   "cause": "createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: Unable to create Enum via index 134, in Id, Index, Raw, Address32, Address20",
   "stack": "Error: createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: Unable to create Enum via index 134, in Id, Index, Raw, Address32, Address20
    at createTypeUnsafe (/build/polkadot/sidecar/node_modules/@polkadot/types/create/createType.js:72:11)
    at createType (/build/polkadot/sidecar/node_modules/@polkadot/types/create/createType.js:84:10)
    at TypeRegistry.createType (/build/polkadot/sidecar/node_modules/@polkadot/types/create/registry.js:297:39)
    at Function._newFromValue (/build/polkadot/sidecar/node_modules/@polkadot/types/extrinsic/Extrinsic.js:202:21)
    at Function._decodeU8a (/build/polkadot/sidecar/node_modules/@polkadot/types/extrinsic/Extrinsic.js:233:29)
    at Function._decodeExtrinsic (/build/polkadot/sidecar/node_modules/@polkadot/types/extrinsic/Extrinsic.js:212:31)
    at new GenericExtrinsic (/build/polkadot/sidecar/node_modules/@polkadot/types/extrinsic/Extrinsic.js:188:38)
    at new Type (/build/polkadot/sidecar/node_modules/@polkadot/types/create/registry.js:340:16)
    at new Submittable (/build/polkadot/sidecar/node_modules/@polkadot/api/submittable/createClass.js:66:7)
    at ApiPromise._extrinsics (/build/polkadot/sidecar/node_modules/@polkadot/api/submittable/createSubmittable.js:18:23)",
}
```

For dry run I see

```
{
   "code": "500",
   "error": "Unable to dry-run transaction",
   "transaction": "0x3902848638559291b4ab4bfc7f5c1aa898c1f0bf1d09d04b10c9027169d7c5ccb53c0001c6cd2058bbe284bc629bb39226d26c697cee40ff3e5dfa01575e04016600b60c3956120bcf0d925131bffc991450cf9835fb312539d4a9e1e5a3569ad76d3c8b00000004004a83f1c09be797bc3d9adce29818368b276a84e6b545ced492c25c948978d7f80b008cb6611e01",
   "cause": "-32601: Method not found",
   "stack": "Error: -32601: Method not found
```

**Comment by emostov** [comment]
To clarify, what runtime are you making these queries against? Is it Polkadot v28? (A substrate node is essentially capable of executing any runtime.) 

It seems like you are running into issues with having an outdated `Address` type. The newest runtimes (which are currently being tested on Westend) use the `MultiAddress` enum to encode addresses. The 3.0.1 release notes have a little section on how this affects responses: https://github.com/paritytech/substrate-api-sidecar/releases/tag/v3.0.1. Additionally you will need to use api-sidecar v3.0.1 or above.

But tl;dr whatever you are using to build transactions needs take into account the new `MultiAddress` enum to correctly encode the transaction. This should make transactions a byte longer. For example @polkadot/api v3.7.3 and above should correctly make transactions for the newest runtime since it has the `MultiAddress` type definition. Additionally @substrate/txwrapper v3.10.8 will also work for the newest runtimes.

> For dry run I see

You need to make sure your node has the correct RPC endpoints exposed. Some RPC endpoints are considered "unsafe" because they are DOS vectors. [Dry run is considered unsafe.](https://github.com/paritytech/substrate/blob/9b08105b8c7106d723c4f470304ad9e2868569d9/utils/frame/rpc/system/src/lib.rs#L134-L136)

**Comment by emostov** [comment]
Closing due to inactivity
