### ISSUE TITLE
Error when querying /blocks/... endpoints

### ISSUE THREAD

**Issue by CurlyBracketEffect** [paritytech/substrate-api-sidecar#438]
Running a Polkadot archive node on GCP with Sidecar installed on the same instance. 

Getting the following error when querying anything from the /blocks endpoint:

```
2021-02-18 17:34:39 error: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received t
ype bigint (125000000n) 
 TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Re
ceived type bigint (125000000n)
    at Function.byteLength (buffer.js:728:11)
    at passStringToWasm0 (/home/jorrin/sidecar/substrate-api-sidecar/node_modules/@substrate/calc/calc.js:24:24)
    at Function.from_params (/home/jorrin/sidecar/substrate-api-sidecar/node_modules/@substrate/calc/calc.js:158:24)
    at BlocksService.createCalcFee (/home/jorrin/sidecar/substrate-api-sidecar/build/src/services/blocks/BlocksService.js:3
44:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async BlocksService.fetchBlock (/home/jorrin/sidecar/substrate-api-sidecar/build/src/services/blocks/BlocksService.j
s:85:52)
    at async BlocksController.getLatestBlock (/home/jorrin/sidecar/substrate-api-sidecar/build/src/controllers/blocks/Block
sController.js:102:49)
    at async /home/jorrin/sidecar/substrate-api-sidecar/build/src/controllers/AbstractController.js:139:9
2021-02-18 17:34:39 error: GET /blocks/head 500 46ms
```

I have pulled the latest version of Sidecar tried upgrading deps first, then tried deleting and reinstalling them.

All other endpoints are behaving as they should be.

**Comment by TarikGul** [comment]
The error seems to be happening [here](https://github.com/paritytech/substrate-api-sidecar/blob/master/src/services/blocks/BlocksService.ts#L531). 

Interesting. Seems to be complaining about calculating the fee and what is being passed into the rust package `@substrate/calc`. I will have to reproduce this to get a better idea of what is happening. 

I will look into this and keep you updated.

**Comment by CurlyBracketEffect** [comment]
In the end, it was a classic layer 8 error.

Note to self: always remember to ```yarn build``` after downloading new releases.
