### ISSUE TITLE
Unknown types found, no types for BlockLength, BlockWeights, ConsumedWeight, SeatHolder, Voter

### ISSUE THREAD

**Issue by phillux** [paritytech/substrate-api-sidecar#479]
**Description**

Substrate API Sidecar does not connect due to BlockWeights issue

**Steps to Reproduce**

- run polkadot archive node 
- run substrate-api-sidecar

**Expected vs. Actual Behavior**

It should connect, but it doesn't.

`$ substrate-api-sidecar --rpc-cors=all
SAS:
  📦 LOG:
     ✅ LEVEL: "info"
     ✅ JSON: false
     ✅ FILTER_RPC: false
     ✅ STRIP_ANSI: false
  📦 SUBSTRATE:
     ✅ WS_URL: "ws://127.0.0.1:9944"
  📦 EXPRESS:
     ✅ BIND_HOST: "127.0.0.1"
     ✅ PORT: 8080
2021-03-19 13:18:23 warn: API/INIT: RPC methods not decorated: payment_queryFeeDetails, system_addLogFilter, system_resetLogFilter, system_unstable_networkState
2021-03-19 13:18:24 warn: METADATA: Unknown types found, no types for BlockLength, BlockWeights, ConsumedWeight, SeatHolder, Voter
2021-03-19 13:18:24 warn: REGISTRY: Unable to resolve type BlockWeights, it will fail on construction
2021-03-19 13:18:24 error: REGISTRY: Error: Cannot construct unknown type BlockWeights
    at new DoNotConstruct (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/types/primitive/DoNotConstruct.js:21:11)
    at new <anonymous> (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/types/primitive/DoNotConstruct.js:27:9)
    at new Type (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/types/create/registry.js:300:16)
    at initType (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/types/create/createType.js:49:19)
    at createTypeUnsafe (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/types/create/createType.js:68:12)
    at createType (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/types/create/createType.js:83:10)
    at TypeRegistry.createType (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/types/create/registry.js:257:39)
    at /usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/metadata/decorate/consts/fromMetadata.js:27:30
    at Array.reduce (<anonymous>)
    at /usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/metadata/decorate/consts/fromMetadata.js:24:73
2021-03-19 13:18:24 error: API/INIT: Error: FATAL: Unable to initialize the API: createType(BlockWeights):: Cannot construct unknown type BlockWeights
    at EventEmitter.value (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/api/base/Init.js:87:25)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at runNextTicks (node:internal/process/task_queues:63:3)
    at processImmediate (node:internal/timers:437:9)
2021-03-19 13:18:24 error: API/INIT: Error: createType(BlockWeights):: Cannot construct unknown type BlockWeights
    at createTypeUnsafe (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/types/create/createType.js:71:11)
    at createType (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/types/create/createType.js:83:10)
    at TypeRegistry.createType (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/types/create/registry.js:257:39)
    at /usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/metadata/decorate/consts/fromMetadata.js:27:30
    at Array.reduce (<anonymous>)
    at /usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/metadata/decorate/consts/fromMetadata.js:24:73
    at Array.reduce (<anonymous>)
    at constantsFromMeta (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/metadata/decorate/consts/fromMetadata.js:15:36)
    at expandMetadata (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/metadata/decorate/index.js:45:49)
    at ApiPromise.injectMetadata (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/api/base/Decorate.js:182:56)
2021-03-19 13:18:24 error: uncaughtException: FATAL: Unable to initialize the API: createType(BlockWeights):: Cannot construct unknown type BlockWeights
Error: FATAL: Unable to initialize the API: createType(BlockWeights):: Cannot construct unknown type BlockWeights
    at EventEmitter.value (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/api/base/Init.js:87:25)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at runNextTicks (node:internal/process/task_queues:63:3)
    at processImmediate (node:internal/timers:437:9) 
 Error: FATAL: Unable to initialize the API: createType(BlockWeights):: Cannot construct unknown type BlockWeights
    at EventEmitter.value (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/api/base/Init.js:87:25)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at runNextTicks (node:internal/process/task_queues:63:3)
    at processImmediate (node:internal/timers:437:9)
{"error":{},"level":"error","message":"uncaughtException: FATAL: Unable to initialize the API: createType(BlockWeights):: Cannot construct unknown type BlockWeights\nError: FATAL: Unable to initialize the API: createType(BlockWeights):: Cannot construct unknown type BlockWeights\n    at EventEmitter.value (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/api/base/Init.js:87:25)\n    at processTicksAndRejections (node:internal/process/task_queues:94:5)\n    at runNextTicks (node:internal/process/task_queues:63:3)\n    at processImmediate (node:internal/timers:437:9)","stack":"Error: FATAL: Unable to initialize the API: createType(BlockWeights):: Cannot construct unknown type BlockWeights\n    at EventEmitter.value (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/api/base/Init.js:87:25)\n    at processTicksAndRejections (node:internal/process/task_queues:94:5)\n    at runNextTicks (node:internal/process/task_queues:63:3)\n    at processImmediate (node:internal/timers:437:9)","exception":true,"date":"Fri Mar 19 2021 13:18:24 GMT+0100 (Central European Standard Time)","process":{"pid":5782,"uid":1000,"gid":1001,"cwd":"/home/XXX","execPath":"/usr/bin/node","version":"v15.10.0","argv":["/usr/bin/node","/usr/bin/substrate-api-sidecar","--rpc-cors=all"],"memoryUsage":{"rss":120811520,"heapTotal":69267456,"heapUsed":38762192,"external":3747385,"arrayBuffers":269301}},"os":{"loadavg":[1.94,2.13,1.69],"uptime":8005.61},"trace":[{"column":25,"file":"/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/api/base/Init.js","function":"EventEmitter.value","line":87,"method":"value","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":94,"method":null,"native":false},{"column":3,"file":"node:internal/process/task_queues","function":"runNextTicks","line":63,"method":null,"native":false},{"column":9,"file":"node:internal/timers","function":"processImmediate","line":437,"method":null,"native":false}]}
^C2021-03-19 13:18:32 info: Caught interrupt signal, exiting...
`

**Comment by emostov** [comment]
What version of api-sidecar are you running? This only should be an issue with older versions when connecting with polkadot or kusama.
Please make sure you have node version >= 12 and api-sidecar version >= 4.0.1.

**Comment by phillux** [comment]
> Please make sure you have node version >= 12 and api-sidecar version >= 4.0.1.

dumb question but how do i find the version number? no `-v` flag for `substrate-api-sidecar`

also, i installed yesterday via the `yarn global add @substrate/api-sidecar` method.

**Comment by emostov** [comment]
@phillux - Normally you can get the version from the root endpoint, but if the service is not starting the best way might just be to look at the `package.json` `version` field. Based on your error stack it looks like you should be able to do something like `cat /usr/lib/node_modules/@substrate/api-sidecar/package.json`

**Comment by phillux** [comment]
ok, i'm apparently running version 2.0, way behind. i reason i installed using `yarn global add @substrate/api-sidecar` is because i was getting a build error using `git clone` and `yarn build` ... i will create another issue for that issue. also, you should probably get the version on wherever it's stored updated.

**Comment by dvdplm** [comment]
> dumb question but how do i find the version number? no `-v` flag for `substrate-api-sidecar`

I've had the same question actually. Maybe two dumb questioners make a feature request? ;)
