### ISSUE TITLE
Missing types on 0.9.3 with 6.2.3

### ISSUE THREAD

**Issue by Swader** [paritytech/substrate-api-sidecar#568]
Trying to run 6.2.3. against Kusama 0.9.3 and getting:

```
2021-05-27 18:22:36 warn: REGISTRY: Unable to resolve type ActiveIndex, it will fail on construction
2021-05-27 18:22:36 warn: REGISTRY: Unable to resolve type Outcome, it will fail on construction
2021-05-27 18:22:36 warn: REGISTRY: Unable to resolve type PalletId, it will fail on construction
2021-05-27 18:22:36 error: REGISTRY: Error: Cannot construct unknown type PalletId
    at new DoNotConstruct (/usr/local/bin/node_modules/@polkadot/types/primitive/DoNotConstruct.js:21:11)
    at new <anonymous> (/usr/local/bin/node_modules/@polkadot/types/primitive/DoNotConstruct.js:27:9)
    at new Type (/usr/local/bin/node_modules/@polkadot/types/create/registry.js:340:16)
    at initType (/usr/local/bin/node_modules/@polkadot/types/create/createType.js:49:19)
    at createTypeUnsafe (/usr/local/bin/node_modules/@polkadot/types/create/createType.js:69:12)
    at createType (/usr/local/bin/node_modules/@polkadot/types/create/createType.js:84:10)
    at TypeRegistry.createType (/usr/local/bin/node_modules/@polkadot/types/create/registry.js:297:39)
    at /usr/local/bin/node_modules/@polkadot/metadata/decorate/constants/index.js:29:30
    at Array.reduce (<anonymous>)
    at /usr/local/bin/node_modules/@polkadot/metadata/decorate/constants/index.js:26:58
2021-05-27 18:22:36 error: API/INIT: Error: FATAL: Unable to initialize the API: createType(PalletId):: Cannot construct unknown type PalletId
    at EventEmitter.value (/usr/local/bin/node_modules/@polkadot/api/base/Init.js:93:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processImmediate (internal/timers.js:434:9)
2021-05-27 18:22:36 error: API/INIT: Error: createType(PalletId):: Cannot construct unknown type PalletId
    at createTypeUnsafe (/usr/local/bin/node_modules/@polkadot/types/create/createType.js:72:11)
    at createType (/usr/local/bin/node_modules/@polkadot/types/create/createType.js:84:10)
    at TypeRegistry.createType (/usr/local/bin/node_modules/@polkadot/types/create/registry.js:297:39)
    at /usr/local/bin/node_modules/@polkadot/metadata/decorate/constants/index.js:29:30
    at Array.reduce (<anonymous>)
    at /usr/local/bin/node_modules/@polkadot/metadata/decorate/constants/index.js:26:58
    at Array.reduce (<anonymous>)
    at decorateConstants (/usr/local/bin/node_modules/@polkadot/metadata/decorate/constants/index.js:17:18)
    at extractProperties (/usr/local/bin/node_modules/@polkadot/types/create/registry.js:120:53)
    at TypeRegistry.setMetadata (/usr/local/bin/node_modules/@polkadot/types/create/registry.js:456:29)
2021-05-27 18:22:36 error: (node:1010026) UnhandledPromiseRejectionWarning: Error: FATAL: Unable to initialize the API: createType(PalletId):: Cannot construct unknown type PalletId
    at EventEmitter.value (/usr/local/bin/node_modules/@polkadot/api/base/Init.js:93:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processImmediate (internal/timers.js:434:9)
```

**Comment by TarikGul** [comment]
This seems to be an issue with the fact that `@polkadot/api` doesn't have the necessary generated types in v4.11.2 for v9030 yet. To just double check, I will run a dev node with 9030, so that I can reproduce this and check if the beta release contains the types necessary to fix this.

**Comment by emostov** [comment]
I cannot reproduce the issue.

I checked out v0.9.3 from polkadot; compiled and ran the node with `./polkadot --dev --tmp`

Then I started up sidecar with `npx @substrate/api-sidecar@v6.2.3`

Then GET `127.0.0.1:8080/blocks/head` returns a 200 response.

@Swader is sidecar give you a log message like `2021-05-27 14:19:32 info: Version: 6.2.3` at startup?

**Comment by TarikGul** [comment]
Also checked against a v0.9.3 dev node, and was not able to reproduce the issue. It seems my assumption for the types as well in `@polkadot/api` was wrong too and it should be up to date.

**Comment by Swader** [comment]
@emostov if you download and run the 0.9.3 binary and use the substrate-api-sidecar binary, does this setup work?

So

```bash
wget https://github.com/paritytech/polkadot/releases/download/v0.9.3/polkadot
chmod +x polkadot
yarn add @substrate/api-sidecar
./polkadot --dev --tmp
./node_modules/.bin/substrate-api-sidecar
```

This should fail with the above errors.

**Comment by Swader** [comment]
Just tried on a new machine, no errors. Strange, need to investigate why it's happening in prod then. Could sidecar be bubbling up to some folders to look for polkadot/api and finding it somewhere else or something similar?

**Comment by TarikGul** [comment]
> Could sidecar be bubbling up to some folders to look for polkadot/api and finding it somewhere else or something similar?

I can see this as an incredibly rare edge case when lets say there's a corrupted node_modules, and node.js keeps propagating up each parent directory tree looking for `@polkadot/api`. But for something like this to happen I would imagine it would have to be the perfect storm for many things. So my overall opinion would be that this is probably not the case.  

That being said, @Swader have you run into any similar issues for sidecar v7.0.1, or any other releases?

**Comment by Swader** [comment]
I'll post back if I do, until then we can close this
