### ISSUE TITLE
[ERROR]: Unable decode storage assets.asset:: createType(AssetDetails)

### ISSUE THREAD

**Issue by TarikGul** [paritytech/substrate-api-sidecar#574]
**Description**

local Path: `http://127.0.0.1:8080/pallets/assets/8/asset-info`
rpc-endpoint: `wss://westend-shell-rpc.parity.io`
Sidecar-version: 7.0.0

This happens when querying the most recently launched `westmine`.

### Log
```
{"code":500,"message":"Unable to decode storage assets.asset:: createType(AssetDetails):: {\"owner\":\"AccountId\",\"issuer\":\"AccountId\",\"admin\":\"AccountId\",\"freezer\":\"AccountId\",\"supply\":\"TAssetBalance\",\"deposit\":\"TAssetDepositBalance\",\"minBalance\":\"TAssetBalance\",\"isSufficient\":\"bool\",\"accounts\":\"u32\",\"sufficients\":\"u32\",\"approvals\":\"u32\",\"isFrozen\":\"bool\"}:: Decoded input doesn't match input, received 0x1299557001f55815d3fcb53c74463acb0cf6d14d4639b340982c60877f384609…0000e80300000000000000000000000000000001000000000000000000000000 (190 bytes), created 0x1299557001f55815d3fcb53c74463acb0cf6d14d4639b340982c60877f384609…000000407a10f35a000000000000000000000003000000000000000000000000 (174 bytes)","stack":"Error: Unable to decode storage assets.asset:: createType(AssetDetails):: {\"owner\":\"AccountId\",\"issuer\":\"AccountId\",\"admin\":\"AccountId\",\"freezer\":\"AccountId\",\"supply\":\"TAssetBalance\",\"deposit\":\"TAssetDepositBalance\",\"minBalance\":\"TAssetBalance\",\"isSufficient\":\"bool\",\"accounts\":\"u32\",\"sufficients\":\"u32\",\"approvals\":\"u32\",\"isFrozen\":\"bool\"}:: Decoded input doesn't match input, received 0x1299557001f55815d3fcb53c74463acb0cf6d14d4639b340982c60877f384609…0000e80300000000000000000000000000000001000000000000000000000000 (190 bytes), created 0x1299557001f55815d3fcb53c74463acb0cf6d14d4639b340982c60877f384609…000000407a10f35a000000000000000000000003000000000000000000000000 (174 bytes)\n    at RpcCore._newType (/Users/tarik/Desktop/parity/substrate-api-sidecar/node_modules/@polkadot/rpc-core/index.cjs:457:13)\n    at RpcCore._formatStorageData (/Users/tarik/Desktop/parity/substrate-api-sidecar/node_modules/@polkadot/rpc-core/index.cjs:391:17)\n    at RpcCore._formatOutput (/Users/tarik/Desktop/parity/substrate-api-sidecar/node_modules/@polkadot/rpc-core/index.cjs:368:19)\n    at callWithRegistry (/Users/tarik/Desktop/parity/substrate-api-sidecar/node_modules/@polkadot/rpc-core/index.cjs:247:42)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","level":"error"}
```

Need to reproduce with a simple example.

**Comment by TarikGul** [comment]
This issue is solved with `@polkadot/api@4.12.2-6`
