### ISSUE TITLE
Enum error when running v8.0.3 locally against 0.9.8

### ISSUE THREAD

**Issue by ngallagher** [paritytech/substrate-api-sidecar#608]
**Description**

The following error occurs when running against version 0.9.8 

2021-07-14 15:20:40 error: REGISTRY: Error: Unable to create Enum via index 13, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12
    at assert (/usr/src/app/node_modules/@polkadot/util/assert.cjs:34:11)
    at createFromValue (/usr/src/app/node_modules/@polkadot/types/codec/Enum.cjs:87:20)
    at decodeFromValue (/usr/src/app/node_modules/@polkadot/types/codec/Enum.cjs:118:14)
    at decodeEnum (/usr/src/app/node_modules/@polkadot/types/codec/Enum.cjs:142:10)
    at new Enum (/usr/src/app/node_modules/@polkadot/types/codec/Enum.cjs:196:21)
    at new <anonymous> (/usr/src/app/node_modules/@polkadot/types/codec/Enum.cjs:211:9)
    at new Type (/usr/src/app/node_modules/@polkadot/types/create/registry.cjs:349:16)
    at decodeU8a (/usr/src/app/node_modules/@polkadot/types/codec/utils/decodeU8a.cjs:24:19)
    at decodeStruct (/usr/src/app/node_modules/@polkadot/types/codec/Struct.cjs:98:41)
    at new Struct (/usr/src/app/node_modules/@polkadot/types/codec/Struct.cjs:132:26)

**Steps to Reproduce**

git checkout v8.0.3
yarn
yarn build
yarn build:docker
docker run --rm -it -p 8080:8080 --network host substrate-api-sidecar

**Expected vs. Actual Behavior**

When I pull the image directly from the hosted image (i.e no building) and then run the following

docker run --rm -it -p 8080:8080 --network host substrate-api-sidecar

It works fine

**Comment by TarikGul** [comment]
Thanks for filing the issue. Will look into this right now.

**Comment by ngallagher** [comment]
FYI - Tried with master and it worked fine, something seems off with v8.0.3 when used with polkadot using v0.9.8?

**Comment by TarikGul** [comment]
I am trying with v8.0.3 against polkadot v0.9.8 and Im not able to reproduce the issue. I am getting the expected output in the log. 

We did release v8.0.4 today, and since master is working for you, I would suggest upgrading and trying it out. There are a few more things I need to check but I am not perfectly sure why there is a REGISTRY: error regarding the Static Metadata yet for you.

**Comment by TarikGul** [comment]
Closing due to inactivity, if this issue present's itself again please feel free to reopen it.
