### ISSUE TITLE
Unable to list parachains

### ISSUE THREAD

**Issue by kebab-mai-haddi** [paritytech/substrate-api-sidecar#663]
**Description**

I am unable to use the api(`/experimental/paras`) that will enlist all the parachains in a network. Facing the error:
```
Parachains are not yet supported on this network.
```

**Steps to Reproduce**

- Run the full node:
`./target/release/polkadot --chain=kusama`
- Run the Substrate API Sidecar
`substrate-api-sidecar`
- Use the API to fetch parachains
`curl http://127.0.0.1:8080/experimental/paras`

At this point, you will face an error:
- Result of the `curl` request:
```
{"code":500,"message":"Parachains are not yet supported on this network.","stack":"Error: Parachains are not yet supported on this network.\n    at ParasController.checkParasModule (/usr/local/lib/node_modules/@substrate/api-sidecar/build/src/controllers/paras/ParasController.js:46:23)\n    at ParasController.getParas (/usr/local/lib/node_modules/@substrate/api-sidecar/build/src/controllers/paras/ParasController.js:12:18)\n    at /usr/local/lib/node_modules/@substrate/api-sidecar/build/src/controllers/AbstractController.js:159:15\n    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/express/lib/router/layer.js:95:5)\n    at /usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/express/lib/router/index.js:275:10)","level":"error"}
```
- Logs from the Sidecar's shell:
```
2021-09-11 05:37:53 error: Parachains are not yet supported on this network.
 Error: Parachains are not yet supported on this network.
    at ParasController.checkParasModule (/usr/local/lib/node_modules/@substrate/api-sidecar/build/src/controllers/paras/ParasController.js:46:23)
    at ParasController.getParas (/usr/local/lib/node_modules/@substrate/api-sidecar/build/src/controllers/paras/ParasController.js:12:18)
    at /usr/local/lib/node_modules/@substrate/api-sidecar/build/src/controllers/AbstractController.js:159:15
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/express/lib/router/index.js:275:10)
2021-09-11 05:37:53 error: GET /experimental/paras 500 8ms
```

**Comment by TarikGul** [comment]
So currently if you connect to Kusama via: 

``` bash
$ export SAS_SUBSTRATE_WS_URL=wss://kusama-rpc.polkadot.io
$ substrate-api-sidecar
```

and then you `curl http://127.0.0.1:8080/experimental/paras` you will get a successful response. 

In terms of your local node, what kusama runtime version are you running? Also if you are syncing a local node and it is not complete this is a very possible error, because the latest block you have synced might not have the runtime information needed for querying parachains.

**Comment by TarikGul** [comment]
Closing due to being stale for 30 days. Feel free to reopen.
