### ISSUE TITLE
v9.1.10 can not start

### ISSUE THREAD

**Issue by jingniao** [paritytech/substrate-api-sidecar#680]
old substrate-api-sidecar version is v9.1.8
after `npm i -g @substrate/api-sidecar` update to v9.1.10 ,api can not start, ksm and dot both can't start
config with supervisor
```
[program:dot]
command=polkadot --name="viawallet" --chain=polkadot --database=paritydb-experimental --unsafe-pruning --pruning=1000  --base-path=/data3/dot --port 30333 --rpc-port 9933 --ws-port 9944 --ws-external --rpc-external --rpc-cors="all"
[program:dot_api]
environment=SAS_EXPRESS_BIND_HOST=0.0.0.0,SAS_EXPRESS_PORT=8088,SAS_SUBSTRATE_WS_URL=ws://127.0.0.1:9944
command=substrate-api-sidecar
```
log
```log
TypeError: _spec.default[specName] is not iterable
    at getBundleFromSpecName (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/@darwinia/types/mix/index.js:66:29)
    at Object.<anonymous> (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/@darwinia/types/mix/index.js:82:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/apps-config/api/spec/crab.cjs:8:12)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/@darwinia/types/mix/index.js:66
    types: [..._spec.default[specName]].map(version => {
                            ^

TypeError: _spec.default[specName] is not iterable
    at getBundleFromSpecName (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/@darwinia/types/mix/index.js:66:29)
    at Object.<anonymous> (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/@darwinia/types/mix/index.js:82:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/apps-config/api/spec/crab.cjs:8:12)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/@darwinia/types/mix/index.js:66
    types: [..._spec.default[specName]].map(version => {
                            ^

TypeError: _spec.default[specName] is not iterable
    at getBundleFromSpecName (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/@darwinia/types/mix/index.js:66:29)
    at Object.<anonymous> (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/@darwinia/types/mix/index.js:82:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/apps-config/api/spec/crab.cjs:8:12)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
~

```

**Comment by TarikGul** [comment]
@jingniao Thanks for reporting this issue. Looks like it might stem from `@darwinia/types` inside of `@polkadot/apps-config`. Currently looking deeper into the problem, and a resolution.

**Comment by TarikGul** [comment]
v9.1.11 is released and solves this issue.
