### ISSUE TITLE
QueryInfo not working for all extrinsics

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/substrate-api-sidecar#70]
The `queryInfo` enpoint does not return fee information for a subset of transactions. Not sure if this is a Substrate issue or Polkadot JS API issue.

Edit:
- `polkadot v0.8.2 --chain kusama`
- `"@polkadot/api": "^1.17.2"`
```
Block 2603042: Fee error on staking.withdrawUnbonded
Block 2603870: Fee error on staking.withdrawUnbonded
Block 2605012: Fee error on staking.withdrawUnbonded
Block 2605556: Fee error on staking.withdrawUnbonded
Block 2606071: Fee error on staking.withdrawUnbonded
Block 2606490: Fee error on staking.withdrawUnbonded
Block 2606494: Fee error on staking.withdrawUnbonded
Block 2609401: Fee error on electionsPhragmen.reportDefunctVoter
Block 2609891: Fee error on electionsPhragmen.reportDefunctVoter
Block 2609993: Fee error on electionsPhragmen.reportDefunctVoter
Block 2610027: Fee error on electionsPhragmen.reportDefunctVoter
Block 2610041: Fee error on electionsPhragmen.reportDefunctVoter
Block 2610069: Fee error on electionsPhragmen.reportDefunctVoter
Block 2610074: Fee error on electionsPhragmen.reportDefunctVoter
Block 2610079: Fee error on electionsPhragmen.reportDefunctVoter
Block 2610092: Fee error on electionsPhragmen.reportDefunctVoter
Block 2610097: Fee error on electionsPhragmen.reportDefunctVoter
Block 2610131: Fee error on electionsPhragmen.reportDefunctVoter
Block 2610131: Fee error on electionsPhragmen.reportDefunctVoter
Block 2610179: Fee error on electionsPhragmen.removeMember
Block 2610184: Fee error on electionsPhragmen.reportDefunctVoter
Block 2611935: Fee error on democracy.second
Block 2612358: Fee error on democracy.second
Block 2612590: Fee error on staking.withdrawUnbonded
Block 2612797: Fee error on democracy.unlock
Block 2613087: Fee error on staking.withdrawUnbonded
Block 2613416: Fee error on staking.withdrawUnbonded
Block 2617290: Fee error on staking.withdrawUnbonded
Block 2619342: Fee error on staking.withdrawUnbonded
Block 2621370: Fee error on staking.withdrawUnbonded
Block 2625054: Fee error on staking.withdrawUnbonded
Block 2626339: Fee error on staking.withdrawUnbonded
```
Sidecar log is:
```
2020-06-06 16:34:00        RPC-CORE: queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfo:: 2: Unable to query dispatch info.: Error decoding field Call :: Staking.0
Error: 2: Unable to query dispatch info.: Error decoding field Call :: Staking.0
    at RpcCoder._checkError (/home/parity/projects/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/coder/index.js:83:13)
    at RpcCoder.decodeResponse (/home/parity/projects/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/coder/index.js:46:10)
    at WsProvider.value (/home/parity/projects/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/ws/Provider.js:166:90)
    at W3CWebSocket.value [as onmessage] (/home/parity/projects/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/ws/Provider.js:146:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/parity/projects/substrate-api-sidecar/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/home/parity/projects/substrate-api-sidecar/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/parity/projects/substrate-api-sidecar/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.processFrame (/home/parity/projects/substrate-api-sidecar/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /home/parity/projects/substrate-api-sidecar/node_modules/websocket/lib/WebSocketConnection.js:323:40
```

**Comment by danforbes** [comment]
It seems like maybe it is having a hard time decoding something from [the `Call` enum for the Staking pallet](https://substrate.dev/rustdocs/v2.0.0-rc2/pallet_staking/enum.Call.html).

**Comment by joepetrowski** [comment]
Yeah, they are all that (`.0`), but I wonder why it's only for `withdrawUnbonded` and not other staking transactions?
```
2020-06-06 16:22:40        RPC-CORE: queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfo:: 2: Unable to query dispatch info.: Error decoding field Call :: ElectionsPhragmen.0
Error: 2: Unable to query dispatch info.: Error decoding field Call :: ElectionsPhragmen.0
    at RpcCoder._checkError (/home/parity/projects/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/coder/index.js:83:13)
    at RpcCoder.decodeResponse (/home/parity/projects/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/coder/index.js:46:10)
    at WsProvider.value (/home/parity/projects/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/ws/Provider.js:166:90)
    at W3CWebSocket.value [as onmessage] (/home/parity/projects/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/ws/Provider.js:146:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/parity/projects/substrate-api-sidecar/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/home/parity/projects/substrate-api-sidecar/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/parity/projects/substrate-api-sidecar/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.processFrame (/home/parity/projects/substrate-api-sidecar/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /home/parity/projects/substrate-api-sidecar/node_modules/websocket/lib/WebSocketConnection.js:323:40
2020-06-06 16:23:38        RPC-CORE: queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfo:: 2: Unable to query dispatch info.: Error decoding field Call :: Democracy.0
Error: 2: Unable to query dispatch info.: Error decoding field Call :: Democracy.0
    at RpcCoder._checkError (/home/parity/projects/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/coder/index.js:83:13)
    at RpcCoder.decodeResponse (/home/parity/projects/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/coder/index.js:46:10)
    at WsProvider.value (/home/parity/projects/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/ws/Provider.js:166:90)
    at W3CWebSocket.value [as onmessage] (/home/parity/projects/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/ws/Provider.js:146:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/parity/projects/substrate-api-sidecar/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/home/parity/projects/substrate-api-sidecar/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/parity/projects/substrate-api-sidecar/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.processFrame (/home/parity/projects/substrate-api-sidecar/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /home/parity/projects/substrate-api-sidecar/node_modules/websocket/lib/WebSocketConnection.js:323:40
```

**Comment by joepetrowski** [comment]
Closing as Alex's Wasm solution is :fire:
