### ISSUE TITLE
 StorageData:: Unable to decode storage transactionPayment.nextFeeMultiplier:: createType([u8;20]):: Expected at least 20 bytes (160 bits), found 16 bytes

### ISSUE THREAD

**Issue by gx0608** [paritytech/substrate-api-sidecar#708]
**Description**

Polkadot v0.9.11
substrate-api-sidecar v9.2.0

**Steps to Reproduce**

Logs:
2021-10-13 01:50:23 error: GET /blocks/9625127 500 127ms
2021-10-13 01:50:23 error: RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage transactionPayment.nextFeeMultiplier:: createType([u8;20]):: Expected at least 20 bytes (160 bits), found 16 bytes
2021-10-13 01:50:23 error: Unable to decode storage transactionPayment.nextFeeMultiplier:: createType([u8;20]):: Expected at least 20 bytes (160 bits), found 16 bytes
 Error: Unable to decode storage transactionPayment.nextFeeMultiplier:: createType([u8;20]):: Expected at least 20 bytes (160 bits), found 16 bytes
    at RpcCore._newType (/usr/src/app/node_modules/@polkadot/rpc-core/bundle.cjs:450:13)
    at RpcCore._formatStorageData (/usr/src/app/node_modules/@polkadot/rpc-core/bundle.cjs:399:17)
    at RpcCore._formatOutput (/usr/src/app/node_modules/@polkadot/rpc-core/bundle.cjs:376:19)
    at callWithRegistry (/usr/src/app/node_modules/@polkadot/rpc-core/bundle.cjs:255:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

**Comment by TarikGul** [comment]
Hey @gx0608, for ` /blocks/9625127` on kusama I wasn't able to reproduce the issue. Just to confirm as well, this was for Kusama?

**Comment by gx0608** [comment]
> Hey @gx0608, for ` /blocks/9625127` on kusama I wasn't able to reproduce the issue. Just to confirm as well, this was for Kusama?

Yes, it was for Kusama.

I was upgrade Sidecar to v9.2.0 about at the 48 hours before,  the error was discover at the 13 hours before.
