### ISSUE TITLE
Cannot convert metadata from version 14 to 13

### ISSUE THREAD

**Issue by alecalve** [paritytech/substrate-api-sidecar#712]
**Description**

Polkadot 0.9.11
Sidecar 9.2.0

**Steps to Reproduce**

```
 ~ curl http://localhost:9934/pallets/staking/storage/ActiveEra\?at=0
{
	"code": 500,
	"message": "Cannot convert metadata from version 14 to 13",
	"stack": "Error: Cannot convert metadata from version 14 to 13\n    at assert (/home/runner/substrate-api-sidecar/node_modules/@polkadot/util/assert.cjs:34:11)\n    at Map.value (/home/runner/substrate-api-sidecar/node_modules/@polkadot/types/metadata/MetadataVersioned.cjs:64:26)\n    at Map.value (/home/runner/substrate-api-sidecar/node_modules/@polkadot/types/metadata/MetadataVersioned.cjs:74:116)\n    at Map.get asV13 [as asV13] (/home/runner/substrate-api-sidecar/node_modules/@polkadot/types/metadata/MetadataVersioned.cjs:142:85)\n    at PalletsStorageService.findPalletMeta (/home/runner/substrate-api-sidecar/build/src/services/pallets/PalletsStorageService.js:100:54)\n    at PalletsStorageService.fetchStorageItem (/home/runner/substrate-api-sidecar/build/src/services/pallets/PalletsStorageService.js:10:50)\n    at PalletsStorageController.getStorageItem (/home/runner/substrate-api-sidecar/build/src/controllers/pallets/PalletsStorageController.js:30:76)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /home/runner/substrate-api-sidecar/build/src/controllers/AbstractController.js:168:9",
	"level": "error"
}
```

**Expected vs. Actual Behavior**

I'd have expected a non 500 error

**Comment by AnonymMan** [comment]
Same error
