### ISSUE TITLE
get block fail on v10.0.0 & node v0.9.11 (westend)

### ISSUE THREAD

**Issue by BomaxChen** [paritytech/substrate-api-sidecar#716]
hi, there is a problem occurs at westend, here is log below

``` 0|api  | 2021-10-14 04:14:33 error: GET /blocks/head 500 86ms
0|api  | 2021-10-14 04:14:33 error: RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.events:: createType(Vec<FrameSystemEventRecord>):: decodeU8a: failed at 0x0000000000000080… on :: DoNotConstruct: Cannot construct unknown type FrameSystemEventRecord
0|api  | 2021-10-14 04:14:37 error: VEC: Unable to decode on index 1 createType(ExtrinsicV4):: createType(Call):: Call: failed decoding paraInherent.enter:: Struct: failed on args: {"data":"{\"bitfields\":\"Vec<PolkadotPrimitivesV1SignedUncheckedSigned>\",\"backedCandidates\":\"Vec<PolkadotPrimitivesV1BackedCandidate>\",\"disputes\":\"Vec<PolkadotPrimitivesV1DisputeStatementSet>\",\"parentHeader\":\"{\\\"parentHash\\\":\\\"H256\\\",\\\"number\\\":\\\"Compact<u32>\\\",\\\"stateRoot\\\":\\\"H256\\\",\\\"extrinsicsRoot\\\":\\\"H256\\\",\\\"digest\\\":\\\"{\\\\\\\"logs\\\\\\\":\\\\\\\"Vec<SpRuntimeGenericDigestDigestItem>\\\\\\\"}\\\"}\"}"}:: decodeU8a: failed at 0x401401000000009a… on data: {"bitfields":"Vec<PolkadotPrimitivesV1SignedUncheckedSigned>","backedCandidates":"Vec<PolkadotPrimitivesV1BackedCandidate>","disputes":"Vec<PolkadotPrimitivesV1DisputeStatementSet>","parentHeader":"{\"parentHash\":\"H256\",\"number\":\"Compact<u32>\",\"stateRoot\":\"H256\",\"extrinsicsRoot\":\"H256\",\"digest\":\"{\\\"logs\\\":\\\"Vec<SpRuntimeGenericDigestDigestItem>\\\"}\"}"}:: decodeU8a: failed at 0x401401000000009a… on bitfields: Vec<PolkadotPrimitivesV1SignedUncheckedSigned>:: decodeU8a: failed at 0x1401000000009af5… on :: DoNotConstruct: Cannot construct unknown type PolkadotPrimitivesV1SignedUncheckedSigned
0|api  | 2021-10-14 04:14:37 error: RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding paraInherent.enter:: Struct: failed on args: {"data":"{\"bitfields\":\"Vec<PolkadotPrimitivesV1SignedUncheckedSigned>\",\"backedCandidates\":\"Vec<PolkadotPrimitivesV1BackedCandidate>\",\"disputes\":\"Vec<PolkadotPrimitivesV1DisputeStatementSet>\",\"parentHeader\":\"{\\\"parentHash\\\":\\\"H256\\\",\\\"number\\\":\\\"Compact<u32>\\\",\\\"stateRoot\\\":\\\"H256\\\",\\\"extrinsicsRoot\\\":\\\"H256\\\",\\\"digest\\\":\\\"{\\\\\\\"logs\\\\\\\":\\\\\\\"Vec<SpRuntimeGenericDigestDigestItem>\\\\\\\"}\\\"}\"}"}:: decodeU8a: failed at 0x401401000000009a… on data: {"bitfields":"Vec<PolkadotPrimitivesV1SignedUncheckedSigned>","backedCandidates":"Vec<PolkadotPrimitivesV1BackedCandidate>","disputes":"Vec<PolkadotPrimitivesV1DisputeStatementSet>","parentHeader":"{\"parentHash\":\"H256\",\"number\":\"Compact<u32>\",\"stateRoot\":\"H256\",\"extrinsicsRoot\":\"H256\",\"digest\":\"{\\\"logs\\\":\\\"Vec<SpRuntimeGenericDigestDigestItem>\\\"}\"}"}:: decodeU8a: failed at 0x401401000000009a… on bitfields: Vec<PolkadotPrimitivesV1SignedUncheckedSigned>:: decodeU8a: failed at 0x1401000000009af5… on :: DoNotConstruct: Cannot construct unknown type PolkadotPrimitivesV1SignedUncheckedSigned
0|api  | 2021-10-14 04:14:37 error: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding paraInherent.enter:: Struct: failed on args: {"data":"{\"bitfields\":\"Vec<PolkadotPrimitivesV1SignedUncheckedSigned>\",\"backedCandidates\":\"Vec<PolkadotPrimitivesV1BackedCandidate>\",\"disputes\":\"Vec<PolkadotPrimitivesV1DisputeStatementSet>\",\"parentHeader\":\"{\\\"parentHash\\\":\\\"H256\\\",\\\"number\\\":\\\"Compact<u32>\\\",\\\"stateRoot\\\":\\\"H256\\\",\\\"extrinsicsRoot\\\":\\\"H256\\\",\\\"digest\\\":\\\"{\\\\\\\"logs\\\\\\\":\\\\\\\"Vec<SpRuntimeGenericDigestDigestItem>\\\\\\\"}\\\"}\"}"}:: decodeU8a: failed at 0x401401000000009a… on data: {"bitfields":"Vec<PolkadotPrimitivesV1SignedUncheckedSigned>","backedCandidates":"Vec<PolkadotPrimitivesV1BackedCandidate>","disputes":"Vec<PolkadotPrimitivesV1DisputeStatementSet>","parentHeader":"{\"parentHash\":\"H256\",\"number\":\"Compact<u32>\",\"stateRoot\":\"H256\",\"extrinsicsRoot\":\"H256\",\"digest\":\"{\\\"logs\\\":\\\"Vec<SpRuntimeGenericDigestDigestItem>\\\"}\"}"}:: decodeU8a: failed at 0x401401000000009a… on bitfields: Vec<PolkadotPrimitivesV1SignedUncheckedSigned>:: decodeU8a: failed at 0x1401000000009af5… on :: DoNotConstruct: Cannot construct unknown type PolkadotPrimitivesV1SignedUncheckedSigned
0|api  |  Error: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding paraInherent.enter:: Struct: failed on args: {"data":"{\"bitfields\":\"Vec<PolkadotPrimitivesV1SignedUncheckedSigned>\",\"backedCandidates\":\"Vec<PolkadotPrimitivesV1BackedCandidate>\",\"disputes\":\"Vec<PolkadotPrimitivesV1DisputeStatementSet>\",\"parentHeader\":\"{\\\"parentHash\\\":\\\"H256\\\",\\\"number\\\":\\\"Compact<u32>\\\",\\\"stateRoot\\\":\\\"H256\\\",\\\"extrinsicsRoot\\\":\\\"H256\\\",\\\"digest\\\":\\\"{\\\\\\\"logs\\\\\\\":\\\\\\\"Vec<SpRuntimeGenericDigestDigestItem>\\\\\\\"}\\\"}\"}"}:: decodeU8a: failed at 0x401401000000009a… on data: {"bitfields":"Vec<PolkadotPrimitivesV1SignedUncheckedSigned>","backedCandidates":"Vec<PolkadotPrimitivesV1BackedCandidate>","disputes":"Vec<PolkadotPrimitivesV1DisputeStatementSet>","parentHeader":"{\"parentHash\":\"H256\",\"number\":\"Compact<u32>\",\"stateRoot\":\"H256\",\"extrinsicsRoot\":\"H256\",\"digest\":\"{\\\"logs\\\":\\\"Vec<SpRuntimeGenericDigestDigestItem>\\\"}\"}"}:: decodeU8a: failed at 0x401401000000009a… on bitfields: Vec<PolkadotPrimitivesV1SignedUncheckedSigned>:: decodeU8a: failed at 0x1401000000009af5… on :: DoNotConstruct: Cannot construct unknown type PolkadotPrimitivesV1SignedUncheckedSigned
0|api  |     at createTypeUnsafe (/home/user01/substrate-api-sidecar/node_modules/@polkadot/types/create/createType.cjs:68:18)
0|api  |     at TypeRegistry.createTypeUnsafe (/home/user01/substrate-api-sidecar/node_modules/@polkadot/types/create/registry.cjs:364:45)
0|api  |     at RpcCore._formatOutput (/home/user01/substrate-api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:389:21)
0|api  |     at callWithRegistry (/home/user01/substrate-api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:255:42)
0|api  |     at runMicrotasks (<anonymous>)
0|api  |     at processTicksAndRejections (node:internal/process/task_queues:93:5)
0|api  | 2021-10-14 04:14:37 error: GET /blocks/head 500 69ms
0|api  | 2021-10-14 04:14:37 error: RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.events:: createType(Vec<FrameSystemEventRecord>):: decodeU8a: failed at 0x0000000000000080… on :: DoNotConstruct: Cannot construct unknown type FrameSystemEventRecord
```

**Comment by TarikGul** [comment]
Closing due to being stale, and lack of information. Please reopen or file a new issue if this re-appears. 

Current latest release is v11.1.0 and I am not able to reproduce the issue.

**Comment by TarikGul** [comment]
The two decoding issues above are completely separate. One deals with westend `system.events` which was not reproducible, but also westend types are native to polkadot-js. Yours deals with `Karura` which the types are not native to polkadot-js which in turn means you needs to inject the necessary `TypesBundle`.
