### ISSUE TITLE
Timeouts getting blocks with Sidecar v10.0.0, node v0.9.11

### ISSUE THREAD

**Issue by pablojorge** [paritytech/substrate-api-sidecar#719]
We've been experiencing serious timeouts fetching blocks on 9.2.0 and 10.0.0 after runtime v9100/v9110 went live.

Example:

```
"0262c8","2021-10-15T01:10:52Z","2021-10-15 01:10:52 error: GET /blocks/7262958 500 232588ms"
"0262c8","2021-10-15T01:10:52Z","2021-10-15 01:10:52 error: Failed while trying to get the latest header. "
"0262c8","2021-10-15T01:10:52Z"," InternalServerError: Failed while trying to get the latest header."
"0262c8","2021-10-15T01:10:52Z","    at /substrate-sidecar/build/src/controllers/AbstractController.js:104:23"
"0262c8","2021-10-15T01:10:52Z","    at runMicrotasks (<anonymous>)"
"0262c8","2021-10-15T01:10:52Z","    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
"0262c8","2021-10-15T01:10:52Z","    at async BlocksController.getHashForBlock (/substrate-sidecar/build/src/controllers/AbstractController.js:103:32)"
"0262c8","2021-10-15T01:10:52Z","    at async BlocksController.getBlockById (/substrate-sidecar/build/src/controllers/blocks/BlocksController.js:118:26)"
"0262c8","2021-10-15T01:10:52Z","    at async /substrate-sidecar/build/src/controllers/AbstractController.js:168:9"
```

On the node side there are no errors, everything seems fine.

After manually restarting the services (node and sidecar) it goes back to normal, but some hours later we start getting timeouts again.

**Comment by pablojorge** [comment]
This is happening with Polkadot mainnet (the only chain we track), and we run our own internal nodes. In fact the nodes seem to be perfectly fine, and never stop receiving and processing blocks.

Memory patterns are not different from previous versions, so nothing really stands out. I'll collect more logs

**Comment by pablojorge** [comment]
Going back in the logs It seems the issue is that Sidecar for some reason disconnects from the node (we're connecting over websocket), and the timeouts are ridiculously high, so it takes a _lot_ of time to react and reconnect.

Full logs: (using [...] to reduce duplication)
```
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: API-WS: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: RPC-CORE: getMetadata(at?: BlockHash): Metadata:: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: RPC-CORE: getMetadata(at?: BlockHash): Metadata:: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
[...]
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: RPC-CORE: getMetadata(at?: BlockHash): Metadata:: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: RPC-CORE: getMetadata(at?: BlockHash): Metadata:: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: RPC-CORE: getMetadata(at?: BlockHash): Metadata:: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: RPC-CORE: getHeader(hash?: BlockHash): Header:: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: RPC-CORE: getMetadata(at?: BlockHash): Metadata:: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: RPC-CORE: health(): Health:: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: RPC-CORE: getBlockHash(blockNumber?: BlockNumber): BlockHash:: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: RPC-CORE: getBlockHash(blockNumber?: BlockNumber): BlockHash:: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: RPC-CORE: getBlockHash(blockNumber?: BlockNumber): BlockHash:: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: RPC-CORE: getBlockHash(blockNumber?: BlockNumber): BlockHash:: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
[...]
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: RPC-CORE: getBlockHash(blockNumber?: BlockNumber): BlockHash:: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: RPC-CORE: getBlockHash(blockNumber?: BlockNumber): BlockHash:: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: RPC-CORE: getBlockHash(blockNumber?: BlockNumber): BlockHash:: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: RPC-CORE: getHeader(hash?: BlockHash): Header:: WebSocket is not connected"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET "
"0262c8","2021-10-15T01:10:48Z"," Error: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
"0262c8","2021-10-15T01:10:48Z","    at W3CWebSocket.value (/substrate-sidecar/node_modules/@polkadot/rpc-provider/ws/index.cjs:176:23)"
"0262c8","2021-10-15T01:10:48Z","    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/substrate-sidecar/node_modules/yaeti/lib/EventTarget.js:107:17)"
"0262c8","2021-10-15T01:10:48Z","    at W3CWebSocket.onClose (/substrate-sidecar/node_modules/websocket/lib/W3CWebSocket.js:228:10)"
"0262c8","2021-10-15T01:10:48Z","    at WebSocketConnection.<anonymous> (/substrate-sidecar/node_modules/websocket/lib/W3CWebSocket.js:201:17)"
"0262c8","2021-10-15T01:10:48Z","    at WebSocketConnection.emit (node:events:390:28)"
"0262c8","2021-10-15T01:10:48Z","    at WebSocketConnection.handleSocketClose (/substrate-sidecar/node_modules/websocket/lib/WebSocketConnection.js:389:14)"
"0262c8","2021-10-15T01:10:48Z","    at Socket.emit (node:events:390:28)"
"0262c8","2021-10-15T01:10:48Z","    at TCP.<anonymous> (node:net:672:12)"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: GET /blocks/7254021 500 2783379ms"
[...]
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET "
"0262c8","2021-10-15T01:10:48Z"," Error: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
"0262c8","2021-10-15T01:10:48Z","    at W3CWebSocket.value (/substrate-sidecar/node_modules/@polkadot/rpc-provider/ws/index.cjs:176:23)"
"0262c8","2021-10-15T01:10:48Z","    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/substrate-sidecar/node_modules/yaeti/lib/EventTarget.js:107:17)"
"0262c8","2021-10-15T01:10:48Z","    at W3CWebSocket.onClose (/substrate-sidecar/node_modules/websocket/lib/W3CWebSocket.js:228:10)"
"0262c8","2021-10-15T01:10:48Z","    at WebSocketConnection.<anonymous> (/substrate-sidecar/node_modules/websocket/lib/W3CWebSocket.js:201:17)"
"0262c8","2021-10-15T01:10:48Z","    at WebSocketConnection.emit (node:events:390:28)"
"0262c8","2021-10-15T01:10:48Z","    at WebSocketConnection.handleSocketClose (/substrate-sidecar/node_modules/websocket/lib/WebSocketConnection.js:389:14)"
"0262c8","2021-10-15T01:10:48Z","    at Socket.emit (node:events:390:28)"
"0262c8","2021-10-15T01:10:48Z","    at TCP.<anonymous> (node:net:672:12)"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: GET /blocks/7254020 500 2783436ms"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET "
"0262c8","2021-10-15T01:10:48Z"," Error: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
"0262c8","2021-10-15T01:10:48Z","    at W3CWebSocket.value (/substrate-sidecar/node_modules/@polkadot/rpc-provider/ws/index.cjs:176:23)"
"0262c8","2021-10-15T01:10:48Z","    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/substrate-sidecar/node_modules/yaeti/lib/EventTarget.js:107:17)"
"0262c8","2021-10-15T01:10:48Z","    at W3CWebSocket.onClose (/substrate-sidecar/node_modules/websocket/lib/W3CWebSocket.js:228:10)"
"0262c8","2021-10-15T01:10:48Z","    at WebSocketConnection.<anonymous> (/substrate-sidecar/node_modules/websocket/lib/W3CWebSocket.js:201:17)"
"0262c8","2021-10-15T01:10:48Z","    at WebSocketConnection.emit (node:events:390:28)"
"0262c8","2021-10-15T01:10:48Z","    at WebSocketConnection.handleSocketClose (/substrate-sidecar/node_modules/websocket/lib/WebSocketConnection.js:389:14)"
"0262c8","2021-10-15T01:10:48Z","    at Socket.emit (node:events:390:28)"
"0262c8","2021-10-15T01:10:48Z","    at TCP.<anonymous> (node:net:672:12)"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: GET /blocks/7254019 500 2783498ms"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET "
"0262c8","2021-10-15T01:10:48Z"," Error: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: Socket Error: read ECONNRESET"
"0262c8","2021-10-15T01:10:48Z","    at W3CWebSocket.value (/substrate-sidecar/node_modules/@polkadot/rpc-provider/ws/index.cjs:176:23)"
"0262c8","2021-10-15T01:10:48Z","    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/substrate-sidecar/node_modules/yaeti/lib/EventTarget.js:107:17)"
"0262c8","2021-10-15T01:10:48Z","    at W3CWebSocket.onClose (/substrate-sidecar/node_modules/websocket/lib/W3CWebSocket.js:228:10)"
"0262c8","2021-10-15T01:10:48Z","    at WebSocketConnection.<anonymous> (/substrate-sidecar/node_modules/websocket/lib/W3CWebSocket.js:201:17)"
"0262c8","2021-10-15T01:10:48Z","    at WebSocketConnection.emit (node:events:390:28)"
"0262c8","2021-10-15T01:10:48Z","    at WebSocketConnection.handleSocketClose (/substrate-sidecar/node_modules/websocket/lib/WebSocketConnection.js:389:14)"
"0262c8","2021-10-15T01:10:48Z","    at Socket.emit (node:events:390:28)"
"0262c8","2021-10-15T01:10:48Z","    at TCP.<anonymous> (node:net:672:12)"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: GET /blocks/7254018 500 2783647ms"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: Failed while trying to get the latest header. "
"0262c8","2021-10-15T01:10:48Z"," InternalServerError: Failed while trying to get the latest header."
"0262c8","2021-10-15T01:10:48Z","    at /substrate-sidecar/build/src/controllers/AbstractController.js:104:23"
"0262c8","2021-10-15T01:10:48Z","    at runMicrotasks (<anonymous>)"
"0262c8","2021-10-15T01:10:48Z","    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
"0262c8","2021-10-15T01:10:48Z","    at async BlocksController.getHashForBlock (/substrate-sidecar/build/src/controllers/AbstractController.js:103:32)"
"0262c8","2021-10-15T01:10:48Z","    at async BlocksController.getBlockById (/substrate-sidecar/build/src/controllers/blocks/BlocksController.js:118:26)"
"0262c8","2021-10-15T01:10:48Z","    at async /substrate-sidecar/build/src/controllers/AbstractController.js:168:9"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: GET /blocks/7254018 500 2748673ms"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: Failed while trying to get the latest header. "
"0262c8","2021-10-15T01:10:48Z"," InternalServerError: Failed while trying to get the latest header."
"0262c8","2021-10-15T01:10:48Z","    at /substrate-sidecar/build/src/controllers/AbstractController.js:104:23"
"0262c8","2021-10-15T01:10:48Z","    at runMicrotasks (<anonymous>)"
"0262c8","2021-10-15T01:10:48Z","    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
"0262c8","2021-10-15T01:10:48Z","    at async BlocksController.getHashForBlock (/substrate-sidecar/build/src/controllers/AbstractController.js:103:32)"
"0262c8","2021-10-15T01:10:48Z","    at async BlocksController.getBlockById (/substrate-sidecar/build/src/controllers/blocks/BlocksController.js:118:26)"
"0262c8","2021-10-15T01:10:48Z","    at async /substrate-sidecar/build/src/controllers/AbstractController.js:168:9"
"0262c8","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: GET /blocks/7254018 500 2713692ms"
[...]
"4c03e9","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: Failed while trying to get the latest header. "
"4c03e9","2021-10-15T01:10:48Z"," InternalServerError: Failed while trying to get the latest header."
"4c03e9","2021-10-15T01:10:48Z","    at /substrate-sidecar/build/src/controllers/AbstractController.js:104:23"
"4c03e9","2021-10-15T01:10:48Z","    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
"4c03e9","2021-10-15T01:10:48Z","    at async BlocksController.getHashForBlock (/substrate-sidecar/build/src/controllers/AbstractController.js:103:32)"
"4c03e9","2021-10-15T01:10:48Z","    at async BlocksController.getBlockById (/substrate-sidecar/build/src/controllers/blocks/BlocksController.js:118:26)"
"4c03e9","2021-10-15T01:10:48Z","    at async /substrate-sidecar/build/src/controllers/AbstractController.js:168:9"
"4c03e9","2021-10-15T01:10:48Z","2021-10-15 01:10:48 [31merror[39m: GET /blocks/7262528 500 2808235ms"
"4c03e9","2021-10-15T01:10:50Z","2021-10-15 01:10:50 [31merror[39m: API-WS: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: connection failed"
"4c03e9","2021-10-15T01:10:53Z","2021-10-15 01:10:53 [31merror[39m: API-WS: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: connection failed"
"59d435","2021-10-15T01:10:53Z","2021-10-15 01:10:53 [31merror[39m: API-WS: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: connection failed"
"59d435","2021-10-15T01:10:55Z","2021-10-15 01:10:55 [31merror[39m: API-WS: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: connection failed"
"0262c8","2021-10-15T01:10:50Z","2021-10-15 01:10:50 [31merror[39m: Failed while trying to get the latest header. "
"0262c8","2021-10-15T01:10:50Z"," InternalServerError: Failed while trying to get the latest header."
[...]
"0262c8","2021-10-15T01:10:52Z","    at /substrate-sidecar/build/src/controllers/AbstractController.js:104:23"
"0262c8","2021-10-15T01:10:52Z","    at runMicrotasks (<anonymous>)"
"0262c8","2021-10-15T01:10:52Z","    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
"0262c8","2021-10-15T01:10:52Z","    at async BlocksController.getHashForBlock (/substrate-sidecar/build/src/controllers/AbstractController.js:103:32)"
"0262c8","2021-10-15T01:10:52Z","    at async BlocksController.getBlockById (/substrate-sidecar/build/src/controllers/blocks/BlocksController.js:118:26)"
"0262c8","2021-10-15T01:10:52Z","    at async /substrate-sidecar/build/src/controllers/AbstractController.js:168:9"
"0262c8","2021-10-15T01:10:52Z","2021-10-15 01:10:52 [31merror[39m: GET /blocks/7262978 500 112693ms"
"0262c8","2021-10-15T01:10:52Z","2021-10-15 01:10:52 [31merror[39m: Failed while trying to get the latest header. "
"0262c8","2021-10-15T01:10:52Z"," InternalServerError: Failed while trying to get the latest header."
"0262c8","2021-10-15T01:10:52Z","    at /substrate-sidecar/build/src/controllers/AbstractController.js:104:23"
"0262c8","2021-10-15T01:10:52Z","    at runMicrotasks (<anonymous>)"
"0262c8","2021-10-15T01:10:52Z","    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
"0262c8","2021-10-15T01:10:52Z","    at async BlocksController.getHashForBlock (/substrate-sidecar/build/src/controllers/AbstractController.js:103:32)"
"0262c8","2021-10-15T01:10:52Z","    at async BlocksController.getBlockById (/substrate-sidecar/build/src/controllers/blocks/BlocksController.js:118:26)"
"0262c8","2021-10-15T01:10:52Z","    at async /substrate-sidecar/build/src/controllers/AbstractController.js:168:9"
"0262c8","2021-10-15T01:10:52Z","2021-10-15 01:10:52 [31merror[39m: GET /blocks/7262988 500 52657ms"
"0262c8","2021-10-15T01:10:52Z","2021-10-15 01:10:52 [31merror[39m: API-WS: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: connection failed"
"0262c8","2021-10-15T01:10:55Z","2021-10-15 01:10:55 [31merror[39m: API-WS: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: connection failed"
[...]
"17e64a","2021-10-15T01:11:55Z","SAS:"
"17e64a","2021-10-15T01:11:55Z","  📦 LOG:"
"17e64a","2021-10-15T01:11:55Z","     ✅ LEVEL: ""info"""
"17e64a","2021-10-15T01:11:55Z","     ✅ JSON: false"
"17e64a","2021-10-15T01:11:55Z","     ✅ FILTER_RPC: false"
"17e64a","2021-10-15T01:11:55Z","     ✅ STRIP_ANSI: false"
"17e64a","2021-10-15T01:11:55Z","  📦 SUBSTRATE:"
"17e64a","2021-10-15T01:11:55Z","     ✅ WS_URL: ""ws://coin-node-dot-kilo-rpc.service.consul:9944"""
"17e64a","2021-10-15T01:11:55Z","     ✅ TYPES_BUNDLE: undefined"
"17e64a","2021-10-15T01:11:55Z","     ✅ TYPES_CHAIN: undefined"
"17e64a","2021-10-15T01:11:55Z","     ✅ TYPES_SPEC: undefined"
"17e64a","2021-10-15T01:11:55Z","     ✅ TYPES: undefined"
"17e64a","2021-10-15T01:11:55Z","  📦 EXPRESS:"
"17e64a","2021-10-15T01:11:55Z","     ✅ BIND_HOST: ""0.0.0.0"""
"17e64a","2021-10-15T01:11:55Z","     ✅ PORT: 9080"
"17e64a","2021-10-15T01:11:55Z","2021-10-15 01:11:55 [32minfo[39m: Version: 9.2.0"
"17e64a","2021-10-15T01:11:55Z","2021-10-15 01:11:55 [31merror[39m: API-WS: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: connection failed"
"17e64a","2021-10-15T01:11:58Z","2021-10-15 01:11:58 [31merror[39m: API-WS: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: connection failed"
"ec234e","2021-10-15T01:11:55Z","SAS:"
"ec234e","2021-10-15T01:11:55Z","  📦 LOG:"
"ec234e","2021-10-15T01:11:55Z","     ✅ LEVEL: ""info"""
"ec234e","2021-10-15T01:11:55Z","     ✅ JSON: false"
"ec234e","2021-10-15T01:11:55Z","     ✅ FILTER_RPC: false"
"ec234e","2021-10-15T01:11:55Z","     ✅ STRIP_ANSI: false"
"ec234e","2021-10-15T01:11:55Z","  📦 SUBSTRATE:"
"ec234e","2021-10-15T01:11:55Z","     ✅ WS_URL: ""ws://coin-node-dot-kilo-rpc.service.consul:9944"""
"ec234e","2021-10-15T01:11:55Z","     ✅ TYPES_BUNDLE: undefined"
"ec234e","2021-10-15T01:11:55Z","     ✅ TYPES_CHAIN: undefined"
"ec234e","2021-10-15T01:11:55Z","     ✅ TYPES_SPEC: undefined"
"ec234e","2021-10-15T01:11:55Z","     ✅ TYPES: undefined"
"ec234e","2021-10-15T01:11:55Z","  📦 EXPRESS:"
"ec234e","2021-10-15T01:11:55Z","     ✅ BIND_HOST: ""0.0.0.0"""
"ec234e","2021-10-15T01:11:55Z","     ✅ PORT: 9080"
"ec234e","2021-10-15T01:11:55Z","2021-10-15 01:11:55 [32minfo[39m: Version: 9.2.0"
"ec234e","2021-10-15T01:11:55Z","2021-10-15 01:11:55 [31merror[39m: API-WS: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: connection failed"
"ec234e","2021-10-15T01:11:57Z","2021-10-15 01:11:57 [31merror[39m: API-WS: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: connection failed"
"c4492a","2021-10-15T01:11:55Z","SAS:"
"c4492a","2021-10-15T01:11:55Z","  📦 LOG:"
"c4492a","2021-10-15T01:11:55Z","     ✅ LEVEL: ""info"""
"c4492a","2021-10-15T01:11:55Z","     ✅ JSON: false"
"c4492a","2021-10-15T01:11:55Z","     ✅ FILTER_RPC: false"
"c4492a","2021-10-15T01:11:55Z","     ✅ STRIP_ANSI: false"
"c4492a","2021-10-15T01:11:55Z","  📦 SUBSTRATE:"
"c4492a","2021-10-15T01:11:55Z","     ✅ WS_URL: ""ws://coin-node-dot-kilo-rpc.service.consul:9944"""
"c4492a","2021-10-15T01:11:55Z","     ✅ TYPES_BUNDLE: undefined"
"c4492a","2021-10-15T01:11:55Z","     ✅ TYPES_CHAIN: undefined"
"c4492a","2021-10-15T01:11:55Z","     ✅ TYPES_SPEC: undefined"
"c4492a","2021-10-15T01:11:55Z","     ✅ TYPES: undefined"
"c4492a","2021-10-15T01:11:55Z","  📦 EXPRESS:"
"c4492a","2021-10-15T01:11:55Z","     ✅ BIND_HOST: ""0.0.0.0"""
"c4492a","2021-10-15T01:11:55Z","     ✅ PORT: 9080"
"c4492a","2021-10-15T01:11:55Z","2021-10-15 01:11:55 [32minfo[39m: Version: 9.2.0"
"c4492a","2021-10-15T01:11:55Z","2021-10-15 01:11:55 [31merror[39m: API-WS: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: connection failed"
"c4492a","2021-10-15T01:11:57Z","2021-10-15 01:11:57 [31merror[39m: API-WS: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: connection failed"
[...]
"ec234e","2021-10-15T01:16:24Z","2021-10-15 01:16:24 [32minfo[39m: Connected to chain Polkadot on the parity-polkadot client at ws://coin-node-dot-kilo-rpc.service.consul:9944"
"ec234e","2021-10-15T01:16:24Z","2021-10-15 01:16:24 [33mwarn[39m: Using unencrypted connection to a public node (ws://coin-node-dot-kilo-rpc.service.consul:9944); All traffic is sent over the internet in cleartext."
"ec234e","2021-10-15T01:16:24Z","2021-10-15 01:16:24 [32minfo[39m: Listening on http://0.0.0.0:9080/"
"ec234e","2021-10-15T01:16:24Z","2021-10-15 01:16:24 [32minfo[39m: Check the root endpoint (http://0.0.0.0:9080/) to see the available endpoints for the current node"
"c4492a","2021-10-15T01:16:48Z","2021-10-15 01:16:48 [31merror[39m: API-WS: disconnected from ws://coin-node-dot-kilo-rpc.service.consul:9944: 1006:: connection failed"
"c4492a","2021-10-15T01:16:56Z","2021-10-15 01:16:56 [32minfo[39m: Connected to chain Polkadot on the parity-polkadot client at ws://coin-node-dot-kilo-rpc.service.consul:9944"
"c4492a","2021-10-15T01:16:56Z","2021-10-15 01:16:56 [33mwarn[39m: Using unencrypted connection to a public node (ws://coin-node-dot-kilo-rpc.service.consul:9944); All traffic is sent over the internet in cleartext."
"c4492a","2021-10-15T01:16:56Z","2021-10-15 01:16:56 [32minfo[39m: Listening on http://0.0.0.0:9080/"
"c4492a","2021-10-15T01:16:56Z","2021-10-15 01:16:56 [32minfo[39m: Check the root endpoint (http://0.0.0.0:9080/) to see the available endpoints for the current node"
```

**Comment by TarikGul** [comment]
To piggy back on what I just said, we wont be merging that PR too until we are able to reproduce the issue locally. Currently for all my tests the polkadot-js api internally is able to reconnect when the ws connection is dropped, so I will need to be able to isolate this issue first (But the solution is put together more or less).

**Comment by TarikGul** [comment]
@pablojorge Have you tried 11.1.0 or greater since 10.0.0? There have been lots of performance imrpovements I wonder if it had some good residual affects for you?

**Comment by pablojorge** [comment]
We did earlier today, we'll continue monitoring to see if becomes more stable

**Comment by pablojorge** [comment]
@TarikGul after upgrading to v11.1.1, we didn't experience random timeouts again

**Comment by TarikGul** [comment]
@pablojorge Awesome, thanks for letting me know. :)
