### ISSUE TITLE
Sidecar v11.3.2 no longer works with Westend

### ISSUE THREAD

**Issue by gituser** [paritytech/substrate-api-sidecar#785]
**Description**

Sidecar v11.3.2 no longer works with Westend gives an error when querying account balance or blocks:
```
Dec  3 16:41:03 polkadot-testnet-dev sidecar[4608]: #034SAS:
Dec  3 16:41:03 polkadot-testnet-dev sidecar[4608]: #034  📦 LOG:
Dec  3 16:41:03 polkadot-testnet-dev sidecar[4608]:     #034 ✅ LEVEL: "info"
Dec  3 16:41:03 polkadot-testnet-dev sidecar[4608]:     #034 ✅ JSON: false
Dec  3 16:41:03 polkadot-testnet-dev sidecar[4608]:     #034 ✅ FILTER_RPC: false
Dec  3 16:41:03 polkadot-testnet-dev sidecar[4608]:     #034 ✅ STRIP_ANSI: false
Dec  3 16:41:03 polkadot-testnet-dev sidecar[4608]: #034  📦 SUBSTRATE:
Dec  3 16:41:03 polkadot-testnet-dev sidecar[4608]:     #034 ✅ WS_URL: "ws://127.0.0.1:9944"
Dec  3 16:41:03 polkadot-testnet-dev sidecar[4608]:     #034 ✅ TYPES_BUNDLE: undefined
Dec  3 16:41:03 polkadot-testnet-dev sidecar[4608]:     #034 ✅ TYPES_CHAIN: undefined
Dec  3 16:41:03 polkadot-testnet-dev sidecar[4608]:     #034 ✅ TYPES_SPEC: undefined
Dec  3 16:41:03 polkadot-testnet-dev sidecar[4608]:     #034 ✅ TYPES: undefined
Dec  3 16:41:03 polkadot-testnet-dev sidecar[4608]: #034  📦 EXPRESS:
Dec  3 16:41:03 polkadot-testnet-dev sidecar[4608]:     #034 ✅ BIND_HOST: "0.0.0.0"
Dec  3 16:41:03 polkadot-testnet-dev sidecar[4608]:     #034 ✅ PORT: 8080
Dec  3 16:41:03 polkadot-testnet-dev sidecar[4608]: 2021-12-03 16:41:03 #033[32minfo#033[39m: Version: 11.3.2
Dec  3 16:41:04 polkadot-testnet-dev sidecar[4608]: 2021-12-03 16:41:04 #033[32minfo#033[39m: Connected to chain Westend on the parity-westend client at ws://127.0.0.1:9944
Dec  3 16:41:04 polkadot-testnet-dev sidecar[4608]: 2021-12-03 16:41:04 #033[32minfo#033[39m: Listening on http://0.0.0.0:8080/
Dec  3 16:41:04 polkadot-testnet-dev sidecar[4608]: 2021-12-03 16:41:04 #033[32minfo#033[39m: Check the root endpoint (http://0.0.0.0:8080/) to see the available endpoints for the current node
```

**block**:
```
Dec  3 16:40:14 polkadot-testnet-dev sidecar[3658]: 2021-12-03 16:40:14 #033[31merror#033[39m: GET /blocks/head?finalized=true 500 8ms
Dec  3 16:40:14 polkadot-testnet-dev sidecar[3658]: 2021-12-03 16:40:14 #033[31merror#033[39m: RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage session.validators:: createType(PalletStakingUnlockChunk):: DoNotConstruct: Cannot construct unknown type PalletStakingUnlockChunk
Dec  3 16:40:14 polkadot-testnet-dev sidecar[3658]: 2021-12-03 16:40:14 #033[31merror#033[39m: RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.events:: createType(FrameSystemEvent):: DoNotConstruct: Cannot construct unknown type FrameSystemEvent
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]: 2021-12-03 16:41:02 #033[31merror#033[39m: RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.account:: createType(FrameSystemAccountInfo):: DoNotConstruct: Cannot construct unknown type FrameSystemAccountInfo
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]: 2021-12-03 16:41:02 #033[31merror#033[39m: Unable to decode storage system.account:: createType(FrameSystemAccountInfo):: DoNotConstruct: Cannot construct unknown type FrameSystemAccountInfo
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]:  Error: Unable to decode storage system.account:: createType(FrameSystemAccountInfo):: DoNotConstruct: Cannot construct unknown type FrameSystemAccountInfo
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]:     at RpcCore._newType (/home/polkadot/sidecar-v11.3.2/node_modules/@polkadot/rpc-core/bundle.cjs:477:13)
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]:     at RpcCore._formatStorageData (/home/polkadot/sidecar-v11.3.2/node_modules/@polkadot/rpc-core/bundle.cjs:422:17)
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]:     at RpcCore._formatOutput (/home/polkadot/sidecar-v11.3.2/node_modules/@polkadot/rpc-core/bundle.cjs:396:19)
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]:     at RpcCore._formatResult (/home/polkadot/sidecar-v11.3.2/node_modules/@polkadot/rpc-core/bundle.cjs:237:27)
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]:     at callWithRegistry (/home/polkadot/sidecar-v11.3.2/node_modules/@polkadot/rpc-core/bundle.cjs:261:19)
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]:     at runMicrotasks (<anonymous>)
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Account balance**:
```
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]: 2021-12-03 16:41:02 #033[31merror#033[39m: GET /accounts/xxx/balance-info 500 8ms
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]: 2021-12-03 16:41:02 #033[31merror#033[39m: RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.account:: createType(FrameSystemAccountInfo):: DoNotConstruct: Cannot construct unknown type FrameSystemAccountInfo
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]: 2021-12-03 16:41:02 #033[31merror#033[39m: Unable to decode storage system.account:: createType(FrameSystemAccountInfo):: DoNotConstruct: Cannot construct unknown type FrameSystemAccountInfo
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]:  Error: Unable to decode storage system.account:: createType(FrameSystemAccountInfo):: DoNotConstruct: Cannot construct unknown type FrameSystemAccountInfo
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]:     at RpcCore._newType (/home/polkadot/sidecar-v11.3.2/node_modules/@polkadot/rpc-core/bundle.cjs:477:13)
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]:     at RpcCore._formatStorageData (/home/polkadot/sidecar-v11.3.2/node_modules/@polkadot/rpc-core/bundle.cjs:422:17)
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]:     at RpcCore._formatOutput (/home/polkadot/sidecar-v11.3.2/node_modules/@polkadot/rpc-core/bundle.cjs:396:19)
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]:     at RpcCore._formatResult (/home/polkadot/sidecar-v11.3.2/node_modules/@polkadot/rpc-core/bundle.cjs:237:27)
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]:     at callWithRegistry (/home/polkadot/sidecar-v11.3.2/node_modules/@polkadot/rpc-core/bundle.cjs:261:19)
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]:     at runMicrotasks (<anonymous>)
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
Dec  3 16:41:02 polkadot-testnet-dev sidecar[3658]: 2021-12-03 16:41:02 #033[31merror#033[39m: GET /accounts/xxx/balance-info 500 8ms
```

**Steps to Reproduce**

Install latest Sidecar `v11.3.2` with Polkadot `v0.9.13-7d8f00b` and try to fetch latest block or any account balance.

**Comment by gituser** [comment]
Ping @TarikGul @dvdplm @maciejhirsz

**Comment by TarikGul** [comment]
Hey thanks for reporting the issue checking it right now.

**Comment by TarikGul** [comment]
This is a tricky one because I am not able to reproduce. I tested this against westend, kusama, and polkadot v0.9.13.

I queried every historic runtime up to the most recent one, and didnt get any errors. I also isolated `/accounts/{accountId}/balance-info`, and `/blocks/{blockId}` but didnt see any issues. 

I took it a step further and manually polled `/blocks/head` and didnt see any odd behavior either. 

--------

Are you running an archive node, or is this just a local dev node you are launching and testing on?

**Comment by TarikGul** [comment]
Also, just as a sidenote, if the node you are running is actively syncing, behavior like this is not uncommon. It is not recommended to be querying a syncing node. You can use `/node/network` to see if the chain is still syncing (this just performs an rpc system_health call)

**Comment by gituser** [comment]
@TarikGul sorry I think it was my bad.

It seems (for some reason) I've been running old sidecar version hence the error.

Now I see logs are clean and it's working fine on `v11.3.2`, though I was so sure that I did restart the node.

**Comment by TarikGul** [comment]
No worries at all :), glad it's fixed.
