### ISSUE TITLE
Connection dropped by remote peer.

### ISSUE THREAD

**Issue by veydecapia** [paritytech/substrate-api-sidecar#805]
**Description**

Trying to run e2e tests for polkadot
using command: yarn test:init-e2e-tests:polkadot

Getting the below error after about 5 to 10 mins of waiting.
**disconnected from wss://polkadot.api.onfinality.io/public-ws: 1006::Connection dropped by remote peer.** 

<pre><font color="#4E9A06"><b>harvey@harvey-MS-7C92</b></font>:<font color="#3465A4"><b>~/Documents/GitHub/substrate-api-sidecar-v1</b></font>$ yarn test:init-e2e-tests:polkadot
rimraf scripts/build/
tsc 
Building Sidecar...
rimraf build/
tsc
Build Finished
Launching Sidecar...
SAS:
  📦 LOG:
 ✅ LEVEL: &quot;http&quot;
 ✅ JSON: false
     ✅ FILTER_RPC: false
     ✅ STRIP_ANSI: false
  📦 SUBSTRATE:
 ✅ WS_URL: &quot;wss://polkadot.api.onfinality.io/public-ws&quot;
     ✅ TYPES_BUNDLE: undefined
     ✅ TYPES_CHAIN: undefined
     ✅ TYPES_SPEC: undefined
 ✅ TYPES: undefined
  📦 EXPRESS:
 ✅ BIND_HOST: &quot;127.0.0.1&quot;
 ✅ PORT: 8080
2021-12-28 20:09:16 <font color="#4E9A06">info</font>: Version: 11.3.5
2021-12-28 20:12:24 <font color="#CC0000">error</font>: API-WS: disconnected from wss://polkadot.api.onfinality.io/public-ws: 1006:: Connection dropped by remote peer.
2021-12-28 20:12:24 <font color="#CC0000">error</font>: RPC-CORE: subscribeRuntimeVersion(): RuntimeVersion:: disconnected from wss://polkadot.api.onfinality.io/public-ws: 1006:: Connection dropped by remote peer.
2021-12-28 20:12:24 <font color="#CC0000">error</font>: DRR: disconnected from wss://polkadot.api.onfinality.io/public-ws: 1006:: Connection dropped by remote peer.
2021-12-28 20:12:24 <font color="#CC0000">error</font>: RPC-CORE: chain(): Text:: disconnected from wss://polkadot.api.onfinality.io/public-ws: 1006:: Connection dropped by remote peer.
2021-12-28 20:12:24 <font color="#CC0000">error</font>: RPC-CORE: getRuntimeVersion(at?: BlockHash): RuntimeVersion:: disconnected from wss://polkadot.api.onfinality.io/public-ws: 1006:: Connection dropped by remote peer.
2021-12-28 20:12:24 <font color="#CC0000">error</font>: RPC-CORE: subscribeRuntimeVersion(): RuntimeVersion:: disconnected from wss://polkadot.api.onfinality.io/public-ws: 1006:: Connection dropped by remote peer.
2021-12-28 20:12:24 <font color="#4E9A06">info</font>: Error: disconnected from wss://polkadot.api.onfinality.io/public-ws: 1006:: Connection dropped by remote peer.
    at W3CWebSocket.value (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/@polkadot/rpc-provider/ws/index.cjs:197:23)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.&lt;anonymous&gt; (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (node:events:390:28)
    at WebSocketConnection.handleSocketClose (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at TLSSocket.emit (node:events:402:35)
    at node:net:687:12
    at TCP.done (node:_tls_wrap:580:7)
2021-12-28 20:12:24 <font color="#CC0000">error</font>: uncaughtException: disconnected from wss://polkadot.api.onfinality.io/public-ws: 1006:: Connection dropped by remote peer.
Error: disconnected from wss://polkadot.api.onfinality.io/public-ws: 1006:: Connection dropped by remote peer.
    at W3CWebSocket.value (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/@polkadot/rpc-provider/ws/index.cjs:197:23)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.&lt;anonymous&gt; (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (node:events:390:28)
    at WebSocketConnection.handleSocketClose (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at TLSSocket.emit (node:events:402:35)
    at node:net:687:12
    at TCP.done (node:_tls_wrap:580:7) 
 Error: disconnected from wss://polkadot.api.onfinality.io/public-ws: 1006:: Connection dropped by remote peer.
    at W3CWebSocket.value (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/@polkadot/rpc-provider/ws/index.cjs:197:23)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.&lt;anonymous&gt; (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (node:events:390:28)
    at WebSocketConnection.handleSocketClose (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at TLSSocket.emit (node:events:402:35)
    at node:net:687:12
    at TCP.done (node:_tls_wrap:580:7)
{&quot;error&quot;:{},&quot;level&quot;:&quot;error&quot;,&quot;message&quot;:&quot;uncaughtException: disconnected from wss://polkadot.api.onfinality.io/public-ws: 1006:: Connection dropped by remote peer.\nError: disconnected from wss://polkadot.api.onfinality.io/public-ws: 1006:: Connection dropped by remote peer.\n    at W3CWebSocket.value (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/@polkadot/rpc-provider/ws/index.cjs:197:23)\n    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/yaeti/lib/EventTarget.js:107:17)\n    at W3CWebSocket.onClose (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/websocket/lib/W3CWebSocket.js:228:10)\n    at WebSocketConnection.&lt;anonymous&gt; (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/websocket/lib/W3CWebSocket.js:201:17)\n    at WebSocketConnection.emit (node:events:390:28)\n    at WebSocketConnection.handleSocketClose (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/websocket/lib/WebSocketConnection.js:389:14)\n    at TLSSocket.emit (node:events:402:35)\n    at node:net:687:12\n    at TCP.done (node:_tls_wrap:580:7)&quot;,&quot;stack&quot;:&quot;Error: disconnected from wss://polkadot.api.onfinality.io/public-ws: 1006:: Connection dropped by remote peer.\n    at W3CWebSocket.value (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/@polkadot/rpc-provider/ws/index.cjs:197:23)\n    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/yaeti/lib/EventTarget.js:107:17)\n    at W3CWebSocket.onClose (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/websocket/lib/W3CWebSocket.js:228:10)\n    at WebSocketConnection.&lt;anonymous&gt; (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/websocket/lib/W3CWebSocket.js:201:17)\n    at WebSocketConnection.emit (node:events:390:28)\n    at WebSocketConnection.handleSocketClose (/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/websocket/lib/WebSocketConnection.js:389:14)\n    at TLSSocket.emit (node:events:402:35)\n    at node:net:687:12\n    at TCP.done (node:_tls_wrap:580:7)&quot;,&quot;exception&quot;:true,&quot;date&quot;:&quot;Tue Dec 28 2021 20:12:24 GMT+0800 (Philippine Standard Time)&quot;,&quot;process&quot;:{&quot;pid&quot;:4396,&quot;uid&quot;:1000,&quot;gid&quot;:1000,&quot;cwd&quot;:&quot;/home/harvey/Documents/GitHub/substrate-api-sidecar-v1&quot;,&quot;execPath&quot;:&quot;/home/harvey/.nvm/versions/node/v16.13.1/bin/node&quot;,&quot;version&quot;:&quot;v16.13.1&quot;,&quot;argv&quot;:[&quot;/home/harvey/.nvm/versions/node/v16.13.1/bin/node&quot;,&quot;/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/build/src/main.js&quot;],&quot;memoryUsage&quot;:{&quot;rss&quot;:152256512,&quot;heapTotal&quot;:98500608,&quot;heapUsed&quot;:66745048,&quot;external&quot;:3967063,&quot;arrayBuffers&quot;:772201}},&quot;os&quot;:{&quot;loadavg&quot;:[0.46,0.48,0.23],&quot;uptime&quot;:282.14},&quot;trace&quot;:[{&quot;column&quot;:23,&quot;file&quot;:&quot;/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/@polkadot/rpc-provider/ws/index.cjs&quot;,&quot;function&quot;:&quot;W3CWebSocket.value&quot;,&quot;line&quot;:197,&quot;method&quot;:&quot;value&quot;,&quot;native&quot;:false},{&quot;column&quot;:17,&quot;file&quot;:&quot;/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/yaeti/lib/EventTarget.js&quot;,&quot;function&quot;:&quot;W3CWebSocket._dispatchEvent [as dispatchEvent]&quot;,&quot;line&quot;:107,&quot;method&quot;:&quot;_dispatchEvent [as dispatchEvent]&quot;,&quot;native&quot;:false},{&quot;column&quot;:10,&quot;file&quot;:&quot;/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/websocket/lib/W3CWebSocket.js&quot;,&quot;function&quot;:&quot;W3CWebSocket.onClose&quot;,&quot;line&quot;:228,&quot;method&quot;:&quot;onClose&quot;,&quot;native&quot;:false},{&quot;column&quot;:17,&quot;file&quot;:&quot;/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/websocket/lib/W3CWebSocket.js&quot;,&quot;function&quot;:null,&quot;line&quot;:201,&quot;method&quot;:null,&quot;native&quot;:false},{&quot;column&quot;:28,&quot;file&quot;:&quot;node:events&quot;,&quot;function&quot;:&quot;WebSocketConnection.emit&quot;,&quot;line&quot;:390,&quot;method&quot;:&quot;emit&quot;,&quot;native&quot;:false},{&quot;column&quot;:14,&quot;file&quot;:&quot;/home/harvey/Documents/GitHub/substrate-api-sidecar-v1/node_modules/websocket/lib/WebSocketConnection.js&quot;,&quot;function&quot;:&quot;WebSocketConnection.handleSocketClose&quot;,&quot;line&quot;:389,&quot;method&quot;:&quot;handleSocketClose&quot;,&quot;native&quot;:false},{&quot;column&quot;:35,&quot;file&quot;:&quot;node:events&quot;,&quot;function&quot;:&quot;TLSSocket.emit&quot;,&quot;line&quot;:402,&quot;method&quot;:&quot;emit&quot;,&quot;native&quot;:false},{&quot;column&quot;:12,&quot;file&quot;:&quot;node:net&quot;,&quot;function&quot;:null,&quot;line&quot;:687,&quot;method&quot;:null,&quot;native&quot;:false},{&quot;column&quot;:7,&quot;file&quot;:&quot;node:_tls_wrap&quot;,&quot;function&quot;:&quot;TCP.done&quot;,&quot;line&quot;:580,&quot;method&quot;:&quot;done&quot;,&quot;native&quot;:false}]}
</pre>

**Comment by TarikGul** [comment]
Hey @veydecapia, 

Have you tried to run this multiple times, and it drops the remote peer every time? I just ran the tests against polkadot and it connected fine. It might have just been a hiccup in the websocket.

```
Launching Sidecar...
SAS:
  📦 LOG:
 ✅ LEVEL: "http"
     ✅ JSON: false
 ✅ FILTER_RPC: false
     ✅ STRIP_ANSI: false
  📦 SUBSTRATE:
     ✅ WS_URL: "wss://polkadot.api.onfinality.io/public-ws"
 ✅ TYPES_BUNDLE: undefined
     ✅ TYPES_CHAIN: undefined
     ✅ TYPES_SPEC: undefined
     ✅ TYPES: undefined
  📦 EXPRESS:
 ✅ BIND_HOST: "127.0.0.1"
 ✅ PORT: 8080
2021-12-28 08:54:11 info: Version: 11.3.5
2021-12-28 08:54:12 info: Connected to chain Polkadot on the parity-polkadot client at wss://polkadot.api.onfinality.io/public-ws
2021-12-28 08:54:12 info: Listening on http://127.0.0.1:8080/
2021-12-28 08:54:12 info: Check the root endpoint (http://127.0.0.1:8080/) to see the available endpoints for the current node
```

Also, you are able to change the wsUrl via the config file. [https://github.com/paritytech/substrate-api-sidecar/blob/master/scripts/config.ts#L29](https://github.com/paritytech/substrate-api-sidecar/blob/master/scripts/config.ts#L29)

**Comment by veydecapia** [comment]
Yes, I've tried to run multiple times, and Yes, wsUrl is declared properly.
Is this something related to my system? Is there a way we can clear cache, reset on my local, etc.?

```
	polkadot: {
		wsUrl: 'wss://polkadot.api.onfinality.io/public-ws',
		JestProcOpts: {
			...defaultJestOpts,
			args: ['test:e2e-tests', '--chain', 'polkadot'],
		},
		SasStartOpts: defaultSasStartOpts,
	},
```

**Comment by TarikGul** [comment]
```
wss://rpc.polkadot.io
wss://pub.elara.patract.io/polkadot
wss://polkadot.geometry.io/websockets
```

Here's a list of public urls for polkadot. I would try to see if you can connect to one of these addresses. I am not totally sure what is happening on the top level surface so I am going to look further. 

> Is this something related to my system? Is there a way we can clear cache, reset on my local, etc.?

I would say yes if you were connecting to a local node, but I am not sure since its a public global node. 
There is always `yarn cache clean` for reseting your local yarn cache.

**Comment by veydecapia** [comment]
I'm able to connect now, but the connection is intermittent.
