### ISSUE TITLE
Staking Pallets Progress "ValidatorCount" Undefined

### ISSUE THREAD

**Issue by UsamaSultan** [paritytech/substrate-api-sidecar#885]
While querying an era for a block, receivng 500 error as 

{"code":500,"message":"Cannot read properties of undefined (reading 'validatorCount')","stack":"TypeError: Cannot read properties of undefined (reading 'validatorCount')\n    at PalletsStakingProgressService.derivePalletStakingProgress (/usr/local/substrate-api-sidecar-11.3.14/build/src/services/pallets/PalletsStakingProgressService.js:21:39)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async PalletsStakingProgressController.getPalletStakingProgress (/usr/local/substrate-api-sidecar-11.3.14/build/src/controllers/pallets/PalletsStakingProgressController.js:79:65)\n    at async /usr/local/substrate-api-sidecar-11.3.14/build/src/controllers/AbstractController.js:168:9","level":"error"}

URL: */sidecar/pallets/staking/progress?at=706311

**Comment by TarikGul** [comment]
Closing in favor of `https://github.com/paritytech/substrate-api-sidecar/issues/886`
