### ISSUE TITLE
Unable to decode storage transactionPayment.nextFeeMultiplier

### ISSUE THREAD

**Issue by alecalve** [paritytech/substrate-api-sidecar#892]
**Description**

Querying for block 9738714 fails with the following error:

```
Error: Unable to decode storage transactionPayment.nextFeeMultiplier:: createType(PalletBalancesReasons):: {\"_enum\":{\"Fee\":0,\"Misc\":1,\"All\":2}}:: Decoded input doesn't match input, received 0x0010a5d4e80000000000000000000000 (16 bytes), created 0x00 (1 bytes)
    at RpcCore._newType (/home/runner/substrate-api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:477:13)
    at RpcCore._formatStorageData (/home/runner/substrate-api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:423:17)
    at RpcCore._formatOutput (/home/runner/substrate-api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:397:19)
    at RpcCore._formatResult (/home/runner/substrate-api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:222:27)
    at callWithRegistry (/home/runner/substrate-api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:250:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Steps to Reproduce**

With Polkadot 0.9.18 and sidecar 11.3.15:

```
curl http://localhost:8080/blocks/9738714
{"code":500,"message":"Unable to decode storage transactionPayment.nextFeeMultiplier:: createType(PalletBalancesReasons):: {\"_enum\":{\"Fee\":0,\"Misc\":1,\"All\":2}}:: Decoded input doesn't match input, received 0x0010a5d4e80000000000000000000000 (16 bytes), created 0x00 (1 bytes)","stack":"Error: Unable to decode storage transactionPayment.nextFeeMultiplier:: createType(PalletBalancesReasons):: {\"_enum\":{\"Fee\":0,\"Misc\":1,\"All\":2}}:: Decoded input doesn't match input, received 0x0010a5d4e80000000000000000000000 (16 bytes), created 0x00 (1 bytes)\n    at RpcCore._newType (/home/runner/substrate-api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:477:13)\n    at RpcCore._formatStorageData (/home/runner/substrate-api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:423:17)\n    at RpcCore._formatOutput (/home/runner/substrate-api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:397:19)\n    at RpcCore._formatResult (/home/runner/substrate-api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:222:27)\n    at callWithRegistry (/home/runner/substrate-api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:250:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","level":"error"}
```

**Comment by alecalve** [comment]
It's our local node that has been upgraded from Polkadot 0.9.16/ Sidecar 11.3.14 5 days ago.

It's been upgraded multiple times over the months/years.

**Comment by alecalve** [comment]
We run it in docker-compose and build each version using this Dockerfile:

```Dockerfile
FROM node:16-alpine

RUN apk add -U git

RUN adduser -D runner
USER runner

ARG VERSION
RUN git clone --branch v${VERSION} --depth 1 https://github.com/paritytech/substrate-api-sidecar.git /home/runner/substrate-api-sidecar

WORKDIR /home/runner/substrate-api-sidecar

RUN set -ex; \
  yarn; \
  yarn run build

ENTRYPOINT ["yarn", "run", "main"]
```

**Comment by TarikGul** [comment]
Sweet, thanks for that. I'll have a look into docker as well, though i suppose it wont actually be the root of this specific issue. 
I have an isolated local node I use for cases like these, once it catches up to the head (syncing), ill also have a look at it in there for 0.9.18 too

**Comment by alecalve** [comment]
I'll try resyncing a node from scratch to see if it will work

**Comment by alecalve** [comment]
resyncing the node made it work again

**Comment by TarikGul** [comment]
Yea weirdly enough I havent been able to reproduce it still even in my test enviornment. 

If you query `/runtime/metadata` are you able to quick search and find `NextFeeMultiplier`?

**Comment by TarikGul** [comment]
Closing as this has been resolved.

**Comment by alecalve** [comment]
I unfortunately didn't think of keeping a copy of one of the old node's datadir for a post-mortem
