### ISSUE TITLE
Failed to submit transaction(ASTR), Error: "Immediately Dropped: The transaction couldn't enter the pool because of the limit"

### ISSUE THREAD

**Issue by tobelangbowan** [paritytech/substrate-api-sidecar#933]
**Description**
substrtate-api-sidecar version: 12.0.0
Astar OnFinality: wss://astar.api.onfinality.io/public-ws

**Steps to Reproduce**
2022-05-27 10:20:34 error: RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1016: Immediately Dropped: The transaction couldn't enter the pool because of the limit
2022-05-27 10:20:34 error: Failed to submit transaction.
 Cause: 1016: Immediately Dropped: The transaction couldn't enter the pool because of the limit
 Transaction: 0x4d028400386e77c4dd03516915acffdd5790d90e5b2697b27ecbe7728eddb1cccd06d74a00e847c595a862caa657bbb68b02716234604d8ae1d9c9710edafa16027746207c0d4d6508e8bee0527e5023631d8d2b7e676671d2a63d30c3163f59de8cf78300850104001f00005ae36746a79f0f8f5b9ed585824b13191c53c60445b7aacf536eb17b1fd01ef3130000c84e676dc11b 
 RpcError: 1016: Immediately Dropped: The transaction couldn't enter the pool because of the limit
    at checkError (/usr/local/share/.config/yarn/global/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:34:11)
    at RpcCoder.decodeResponse (/usr/local/share/.config/yarn/global/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:47:5)
    at WsProvider.value (/usr/local/share/.config/yarn/global/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:297:90)
    at W3CWebSocket.value [as onmessage] (/usr/local/share/.config/yarn/global/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:277:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/usr/local/share/.config/yarn/global/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/usr/local/share/.config/yarn/global/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:375:28)
    at WebSocketConnection.processFrame (/usr/local/share/.config/yarn/global/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /usr/local/share/.config/yarn/global/node_modules/websocket/lib/WebSocketConnection.js:323:40

**Comment by tobelangbowan** [comment]
Already resolved, tip needs to be added to execute the transaction
