### ISSUE TITLE
Error in querying account information

### ISSUE THREAD

**Issue by tianfufeng** [paritytech/substrate-api-sidecar#960]
SAS:
  ð¦ LOG:
     ✅ LEVEL: "info"
     ✅ JSON: false
     ✅ FILTER_RPC: false
     ✅ STRIP_ANSI: false
  ð¦ SUBSTRATE:
     ✅ WS_URL: "ws://127.0.0.1:9922"
     ✅ TYPES_BUNDLE: undefined
     ✅ TYPES_CHAIN: undefined
     ✅ TYPES_SPEC: undefined
     ✅ TYPES: "/data/blockdata/cere/my-chains-types.json"
  ð¦ EXPRESS:
     ✅ BIND_HOST: "127.0.0.1"
     ✅ PORT: 9921
2022-06-15 17:23:48 info: Version: 12.1.1
2022-06-15 17:23:48 info: Connected to chain Cere Mainnet Beta on the substrate-node client at ws://127.0.0.1:9922
2022-06-15 17:23:48 info: Listening on http://127.0.0.1:9921/
2022-06-15 17:23:48 info: Check the root endpoint (http://127.0.0.1:9921/) to see the available endpoints for the current node
2022-06-15 17:24:00 error: RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.account:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0a000000000000008295d81b1000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (72 bytes), created 0x0a000000000000008295d81b1000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes)
2022-06-15 17:24:00 error: Unable to decode storage system.account:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0a000000000000008295d81b1000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (72 bytes), created 0x0a000000000000008295d81b1000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes) 
 BadRequestError: Unable to decode storage system.account:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0a000000000000008295d81b1000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (72 bytes), created 0x0a000000000000008295d81b1000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes)
    at AccountsBalanceInfoService.createHttpErrorForAddr (/data/blockdata/cere/substrate-api-sidecar/substrate-api-sidecar/node_modules/@substrate/api-sidecar/build/src/services/AbstractService.js:57:16)
    at /data/blockdata/cere/substrate-api-sidecar/substrate-api-sidecar/node_modules/@substrate/api-sidecar/build/src/services/accounts/AccountsBalanceInfoService.js:86:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AccountsBalanceInfoService.fetchAccountBalanceInfo (/data/blockdata/cere/substrate-api-sidecar/substrate-api-sidecar/node_modules/@substrate/api-sidecar/build/src/services/accounts/AccountsBalanceInfoService.js:81:50)
    at async AccountsBalanceController.getAccountBalanceInfo (/data/blockdata/cere/substrate-api-sidecar/substrate-api-sidecar/node_modules/@substrate/api-sidecar/build/src/controllers/accounts/AccountsBalanceInfoController.js:74:58)
    at async /data/blockdata/cere/substrate-api-sidecar/substrate-api-sidecar/node_modules/@substrate/api-sidecar/build/src/controllers/AbstractController.js:183:9
2022-06-15 17:24:00 warn: GET /accounts/5GWjiHMxHbgR9ADLiJeMhjKFzaSFtrFPiL4Q4FBHC5smf1RW/balance-info 400 31ms

my-chains-types.json:
{
  "ChainId": "u8",
  "DepositNonce": "u64",
  "ResourceId": "[u8; 32]",
  "ProposalStatus": {
    "_enum": [
      "Initiated",
      "Approved",
      "Rejected"
    ]
  },
  "ProposalVotes": {
    "votes_for": "Vec<AccountId>",
    "votes_against": "Vec<AccountId>",
    "status": "ProposalStatus",
    "expiry": "BlockNumber"
  },
  "TokenId": "u256",
  "Erc721Token": {
    "id": "TokenId",
    "metadata": "Vec<u8>"
  },
  "Address": "IndicesLookupSource",
  "LookupSource": "IndicesLookupSource"
}

**Comment by tianfufeng** [comment]
Yes, the node we are linking is cere, and we cannot provide a testable node for the time being. I am also testing locally, and it is not online yet.

**Comment by TarikGul** [comment]
Yea unless I can reproduce it, I cant be much help. Can you point me to the repo your node is located at.

**Comment by tianfufeng** [comment]
Thanks a lot for your help, I downgraded the version and it works now
